### ISSUE TITLE
could the envoy log level be setted

### ISSUE THREAD

**Issue by ssucker** [kubenetworks/kubevpn#123]
For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
```golang
        ...
	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
		Name:  config.ContainerSidecarEnvoyProxy,
		Image: config.Image,
		Command: []string{
			"envoy",
			"-l",
			"error",
			"--base-id",
			"1",
			"--service-node",
			nodeId,
			"--service-cluster",
			nodeId,
			"--config-yaml",
		},
		Args: []string{
			string(envoyConfig),
		},
        ...
```
could this param be set like config.Image. So user  are able to inject this log level when build a kubevpn.exe.

**Comment by ssucker** [comment]
Since sometime i wanna see if the sended request go to pod with headers successfully, but envoy with error log level shows nothing.

**Comment by wencaiwulue** [comment]
> For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
> 
> ```go
>         ...
> 	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
> 		Name:  config.ContainerSidecarEnvoyProxy,
> 		Image: config.Image,
> 		Command: []string{
> 			"envoy",
> 			"-l",
> 			"error",
> 			"--base-id",
> 			"1",
> 			"--service-node",
> 			nodeId,
> 			"--service-cluster",
> 			nodeId,
> 			"--config-yaml",
> 		},
> 		Args: []string{
> 			string(envoyConfig),
> 		},
>         ...
> ```
> 
> could this param be set like config.Image. So user are able to inject this log level when build a kubevpn.exe.

Yes, it's a good idea. at the begining, i set log level to debug, but my colleague said，it show too log not necessary. so i changed it to level error. make it dynamic is a good idea. i will fix it as soon as possible

**Comment by wencaiwulue** [comment]
> Since sometime i wanna see if the sended request go to pod with headers successfully, but envoy with error log level shows nothing.



> For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
> 
> ```go
>         ...
> 	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
> 		Name:  config.ContainerSidecarEnvoyProxy,
> 		Image: config.Image,
> 		Command: []string{
> 			"envoy",
> 			"-l",
> 			"error",
> 			"--base-id",
> 			"1",
> 			"--service-node",
> 			nodeId,
> 			"--service-cluster",
> 			nodeId,
> 			"--config-yaml",
> 		},
> 		Args: []string{
> 			string(envoyConfig),
> 		},
>         ...
> ```
> 
> could this param be set like config.Image. So user are able to inject this log level when build a kubevpn.exe.

I set envoy log level by `kubevpn proxy deployment/authors --headers a=1 --debug`, use `--debug` flag to special envoy log level, same like `--image`, you can overwrite config.image by `kubevpn connect --image myregistry.io/kubevpn/kubevpn:latest` use ourself image to startup pod `kubevpn-traffic-manager`

**Comment by ssucker** [comment]
> > Since sometime i wanna see if the sended request go to pod with headers successfully, but envoy with error log level shows nothing.
> 
> > For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
> > ```go
> >         ...
> > 	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
> > 		Name:  config.ContainerSidecarEnvoyProxy,
> > 		Image: config.Image,
> > 		Command: []string{
> > 			"envoy",
> > 			"-l",
> > 			"error",
> > 			"--base-id",
> > 			"1",
> > 			"--service-node",
> > 			nodeId,
> > 			"--service-cluster",
> > 			nodeId,
> > 			"--config-yaml",
> > 		},
> > 		Args: []string{
> > 			string(envoyConfig),
> > 		},
> >         ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > could this param be set like config.Image. So user are able to inject this log level when build a kubevpn.exe.
> 
> I set envoy log level by `kubevpn proxy deployment/authors --headers a=1 --debug` use `--debug` flag to special envoy log level, same like `--image` you can overwrite config.image by `kubevpn connect --image myregistry.io/kubevpn/kubevpn:latest` use ourself image to startup pod `kubevpn-traffic-manager`

Wow, awesome!!!

**Comment by wencaiwulue** [comment]
> > > Since sometime i wanna see if the sended request go to pod with headers successfully, but envoy with error log level shows nothing.
> > 
> > 
> > > For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
> > > ```go
> > >         ...
> > > 	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
> > > 		Name:  config.ContainerSidecarEnvoyProxy,
> > > 		Image: config.Image,
> > > 		Command: []string{
> > > 			"envoy",
> > > 			"-l",
> > > 			"error",
> > > 			"--base-id",
> > > 			"1",
> > > 			"--service-node",
> > > 			nodeId,
> > > 			"--service-cluster",
> > > 			nodeId,
> > > 			"--config-yaml",
> > > 		},
> > > 		Args: []string{
> > > 			string(envoyConfig),
> > > 		},
> > >         ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > could this param be set like config.Image. So user are able to inject this log level when build a kubevpn.exe.
> > 
> > 
> > I set envoy log level by `kubevpn proxy deployment/authors --headers a=1 --debug` use `--debug` flag to special envoy log level, same like `--image` you can overwrite config.image by `kubevpn connect --image myregistry.io/kubevpn/kubevpn:latest` use ourself image to startup pod `kubevpn-traffic-manager`
> 
> Wow, awesome!!!

I am redo releaseing v2.2.1, please wait it finished, in 30 min

**Comment by wencaiwulue** [comment]
> > > > Since sometime i wanna see if the sended request go to pod with headers successfully, but envoy with error log level shows nothing.
> > > 
> > > 
> > > > For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
> > > > ```go
> > > >         ...
> > > > 	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
> > > > 		Name:  config.ContainerSidecarEnvoyProxy,
> > > > 		Image: config.Image,
> > > > 		Command: []string{
> > > > 			"envoy",
> > > > 			"-l",
> > > > 			"error",
> > > > 			"--base-id",
> > > > 			"1",
> > > > 			"--service-node",
> > > > 			nodeId,
> > > > 			"--service-cluster",
> > > > 			nodeId,
> > > > 			"--config-yaml",
> > > > 		},
> > > > 		Args: []string{
> > > > 			string(envoyConfig),
> > > > 		},
> > > >         ...
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > could this param be set like config.Image. So user are able to inject this log level when build a kubevpn.exe.
> > > 
> > > 
> > > I set envoy log level by `kubevpn proxy deployment/authors --headers a=1 --debug` use `--debug` flag to special envoy log level, same like `--image` you can overwrite config.image by `kubevpn connect --image myregistry.io/kubevpn/kubevpn:latest` use ourself image to startup pod `kubevpn-traffic-manager`
> > 
> > 
> > Wow, awesome!!!
> 
> I am redo releaseing v2.2.1, please wait it finished, in 30 min

release v2.2.1 have been released, you can download it from [link](https://github.com/kubenetworks/kubevpn/releases/tag/v2.2.1) to have a try

**Comment by wencaiwulue** [comment]
> For now, the AddMeshContainer(pkg/mesh/controller.go:30) func add an envoy sidecar with log level of error.
> 
> ```go
>         ...
> 	spec.Spec.Containers = append(spec.Spec.Containers, v1.Container{
> 		Name:  config.ContainerSidecarEnvoyProxy,
> 		Image: config.Image,
> 		Command: []string{
> 			"envoy",
> 			"-l",
> 			"error",
> 			"--base-id",
> 			"1",
> 			"--service-node",
> 			nodeId,
> 			"--service-cluster",
> 			nodeId,
> 			"--config-yaml",
> 		},
> 		Args: []string{
> 			string(envoyConfig),
> 		},
>         ...
> ```
> 
> could this param be set like config.Image. So user are able to inject this log level when build a kubevpn.exe.

Done ~
