### ISSUE TITLE
[Feature-Request] Also access cloud resources over kubevpn

### ISSUE THREAD

**Issue by 3deep5me** [kubenetworks/kubevpn#132]
Hi all,

first i love your tool! Easy, small and it just works!

Not sure if this is already covered in kubevpn. 

We would like to also access resources which are outside of the cluster but part of the same subnet as the nodes.

Why?
We can easily access kube services and pods but we also need sometimes to directly connect to a database which is sadly not in kubernetes. 

How?
Maybe a kind of vpn tunnel would be useful for something like this. 

What?
To be honest i do not know but i could image to use somehow wireguard, maybe also over a port-forward to build a tunnel to the whole node subnet?

**Comment by wencaiwulue** [comment]
> Hi all,
> 
> first i love your tool! Easy, small and it just works!
> 
> Not sure if this is already covered in kubevpn.
> 
> We would like to also access resources which are outside of the cluster but part of the same subnet as the nodes.
> 
> Why? We can easily access kube services and pods but we also need sometimes to directly connect to a database which is sadly not in kubernetes.
> 
> How? Maybe a kind of vpn tunnel would be useful for something like this.
> 
> What? To be honest i do not know but i could image to use somehow wireguard, maybe also over a port-forward to build a tunnel to the whole node subnet?

it support options `--extra-cidr`, you can use it like `kubevpn connect --extra-cidr 192.168.128.13/32 --extra-cidr 192.168.128.14/32`, and then ,try to ping this two ip `ping 192.168.128.13` or `ping 192.168.128.14` ， it should works fine ~, and also support `--extra-domain`, like `kubevpn connect -n default --extra-domain mysql10444867794d.mytest.com --extra-cidr 192.168.128.13/32 --extra-cidr 192.168.128.14/32`

**Comment by wencaiwulue** [comment]
> > Hi all,
> > first i love your tool! Easy, small and it just works!
> > Not sure if this is already covered in kubevpn.
> > We would like to also access resources which are outside of the cluster but part of the same subnet as the nodes.
> > Why? We can easily access kube services and pods but we also need sometimes to directly connect to a database which is sadly not in kubernetes.
> > How? Maybe a kind of vpn tunnel would be useful for something like this.
> > What? To be honest i do not know but i could image to use somehow wireguard, maybe also over a port-forward to build a tunnel to the whole node subnet?
> 
> it support options `--extra-cidr`, you can use it like `kubevpn connect --extra-cidr 192.168.128.13/32 --extra-cidr 192.168.128.14/32`, and then ,try to ping this two ip `ping 192.168.128.13` or `ping 192.168.128.14` ， it should works fine ~, and also support `--extra-domain`, like `kubevpn connect -n default --extra-domain mysql10444867794d.mytest.com --extra-cidr 192.168.128.13/32 --extra-cidr 192.168.128.14/32`, you can also ping `ping mysql10444867794d.mytest.com`

**Comment by 3deep5me** [comment]
Amazing thank you! It works like a charm!

**Comment by wencaiwulue** [comment]
> Amazing thank you! It works like a charm!

Maybe you can introduce this tools to your teammate or friends, thanks in advance ~ 🎉

**Comment by wencaiwulue** [comment]
> [@wencaiwulue](https://github.com/wencaiwulue) is there any speciallity for azure databases? Because it works on AWS but on azure when giving `--extra-domain "db-name.postgres.database.azure.com"` I get an error that it can not dig the domain and fails to setup the DNS.
> 
> ```
> Adding extra domain to hosts...
> Add extra route failed: failed to resolve DNS for domain db-name.postgres.database.azure.com by command dig
> Configure DNS failed: failed to resolve DNS for domain db-name.postgres.database.azure.com by command dig
> Failed to connect...
> Performing cleanup operations
> Port forward retrying
> ```

Can you exec command `dig +short db-name.postgres.database.azure.com` in cluster pod?

**Comment by dada-engineer** [comment]
the output is:

```
dig +short db-name.postgres.database.azure.com
1234567.privatelink.db-name.postgres.database.azure.com.
10.0.100.1
```

In fact we also added an additional private zone that is called `this.account` and add a record `db-name.this.account` to point to `db-name.postgres.database.azure.com`

when I do `dig  +short foundation-db.this.account` I get:

```
db-name.postgres.database.azure.com.
1234567.privatelink.db-name.postgres.database.azure.com.
10.0.100.1
```

**Comment by wencaiwulue** [comment]
> the output is:
> 
> ```
> dig +short db-name.postgres.database.azure.com
> 1234567.privatelink.db-name.postgres.database.azure.com.
> 10.0.100.1
> ```
> 
> In fact we also added an additional private zone that is called `this.account` and add a record `db-name.this.account` to point to `db-name.postgres.database.azure.com`
> 
> when I do `dig +short foundation-db.this.account` I get:
> 
> ```
> db-name.postgres.database.azure.com.
> 1234567.privatelink.db-name.postgres.database.azure.com.
> 10.0.100.1
> ```

I see. it's a bug, becase it's a CNAME record, dig output is mutiple line, needs to parse ip from those lines. i commit code to fix this problem, you can clone the repo and checkout the branch to verify it. thanks ~

**Comment by wencaiwulue** [comment]
@dada-engineer already released the new version, you can upgrade and have a try ~

**Comment by dada-engineer** [comment]
> [@dada-engineer](https://github.com/dada-engineer) already released the new version, you can upgrade and have a try ~

Thank you, I am sorry that I did not find the time to test beforehand. It works very well thank you 👍🏻
