### ISSUE TITLE
[Question/Feature-Request] central install of kubevpn-traffic-manager

### ISSUE THREAD

**Issue by 3deep5me** [kubenetworks/kubevpn#133]
Hi again,

Not sure if this is already covered or partly covered in kubevpn.

We would like to install kubevpn-traffic-manager deployment in a central namespace. In best-case with a helm-chart or similar.

Why?
- central update management 
    - we would like to ensure that on every cluster the newest server version is installed
- security
    - the kubevpn-traffic-manager is a privileged deployment
    - we use the restricted profile of the [Pod Security Defaults](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted)  which forbids this 
    - an extra namespace for the kubevpn-traffic-manager would allow us to continue to use the PSD
- resource efficiency
    - we have at least one namespace for each developer (preview-enviroment)
    - with five preview-enviroments we would have a memory footprint of about ~3,5GiB (750MiB per kubevpn instance)

How?
Maybe a flag in the cli to point to the namespace where the kubevpn-traffic-manager is deployed.

What?
If its possible to do something like this and if you may decide to do it - i can offer at least to build a helmchart.

**Comment by wencaiwulue** [comment]
> Hi again,
> 
> Not sure if this is already covered or partly covered in kubevpn.
> 
> We would like to install kubevpn-traffic-manager deployment in a central namespace. In best-case with a helm-chart or similar.
> 
> Why?
> 
> * central update management
>   
>   * we would like to ensure that on every cluster the newest server version is installed
> * security
>   
>   * the kubevpn-traffic-manager is a privileged deployment
>   * we use the restricted profile of the [Pod Security Defaults](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted)  which forbids this
>   * an extra namespace for the kubevpn-traffic-manager would allow us to continue to use the PSD
> * resource efficiency
>   
>   * we have at least one namespace for each developer (preview-enviroment)
>   * with five preview-enviroments we would have a memory footprint of about ~3,5GiB (750MiB per kubevpn instance)
> 
> How? Maybe a flag in the cli to point to the namespace where the kubevpn-traffic-manager is deployed.
> 
> What? If its possible to do something like this and if you may decide to do it - i can offer at least to build a helmchart.

Yes, you can use options `--namespace` or short `-n` to special namespace which pod kubevpn-traffic-manager created,  you can use command `kubevpn options` see more options, just like command `kubectl`

Yes, if you can help to write helm chart, that's very nice, welcome ~, just go go go ~

**Comment by 3deep5me** [comment]
Thanks! I tested it but i think i have an issue with that.
If i use the flag the hosts entries are also from the specified namespace.
I would like to have kubevpn run in namespace A but get the hosts entries from namespace B.
At the moment it seems that I only get the hosts from the namespace in which kubevpn is running.

**Comment by wencaiwulue** [comment]
> Thanks! I tested it but i think i have an issue with that. If i use the flag the hosts entries are also from the specified namespace. I would like to have kubevpn run in namespace A but get the hosts entries from namespace B. At the moment it seems that I only get the hosts from the namespace in which kubevpn is running.

Actually, you can access k8s service with full k8s dns name, eg, if you are connectted to namespace A, you can access namespace service in this way:
```shell
curl SERVICE_NAME.NAMESPACE_B.svc.cluster.local
```
here is doc [kubevpn docs](https://github.com/kubenetworks/kubevpn?tab=readme-ov-file#domain-resolve)

**Comment by wencaiwulue** [comment]
@3deep5me hello, if you want install it now, you can checkout branch `feat/add-manifest-helm-chart` with command 
```shell
git clone --branch feat/add-manifest-helm-chart https://github.com/kubenetworks/kubevpn.git
```
then
```shell
cd kubevpn
```
and use command to install it 
```shell
helm install kubevpn ./charts/kubevpn --set image.tag=test
```
you can special namespace you want, but remember to with `--set image.tag=test`
like:
```
helm install kubevpn ./charts/kubevpn  -n dev --set image.tag=test
```
if you know k8s cluster network service cidr or pod cidr, you can use command:
```shell
helm install kubevpn ./charts/kubevpn  -n dev --set image.tag=test --set cidr.pod=xxxx/xx --set cidr.pod=xxxx/xx
```

finally, you can use command `kubevpn` to connect
```shell
kubevpn connect
```

otherwise, you can wait maybe two weeks to release a new version 2.2.2.

**Comment by 3deep5me** [comment]
thanks @wencaiwulue!
I will try it out properly this week.

**Comment by 3deep5me** [comment]
I just looked into the commit, looks nice so far. I like the HPA 😃.

I noticed a typo on the filename `rulebinding.yaml`.

Another question: Does Kubevpn need the namespace labeling? Because we normal manage our namespaces over gitops and in this case (if not configured)  our gitops controller would remove the addtional label.

**Comment by wencaiwulue** [comment]
> I just looked into the commit, looks nice so far. I like the HPA 😃.
> 
> I noticed a typo on the filename `rulebinding.yaml`.
> 
> Another question: Does Kubevpn need the namespace labeling? Because we normal manage our namespaces over gitops and in this case (if not configured) our gitops controller would remove the additional label.

Yes, i will change `rulebinding.yaml` --> `rolebinding.yaml`.
Kubevpn needs label namespace for webhook to manage ip (rentIP before pod create and release ip after pod destroy), But it also works event without label ns, because i write same logic to rentIP at the begining of pod entrypoint . but i recommend label ns, just let all thing goes smoothly

**Comment by wencaiwulue** [comment]
@3deep5me i finished this feature in pr https://github.com/kubenetworks/kubevpn/pull/145 , you can install it by following doc: [link](https://www.kubevpn.cn/docs/quickstart/)

**Comment by 3deep5me** [comment]
Thanks a lot!

**Comment by wencaiwulue** [comment]
@3deep5me in this pr https://github.com/kubenetworks/kubevpn/pull/177. add the feature to detect pod/service cidr logic, after pod have been started in cluster, client will do nothing just connect to kubevpn-traffic-manager pod. let things became more easy ~, already released new version, you can have a try ~

**Comment by wencaiwulue** [comment]
@3deep5me we support this feature now. you can use version v2.4.3, use helm to install kubevpn server and mutilpe users will use this server, no more to create kubevpn deployment to each other namespce. remember use helm to install it. we implement this feature by commit https://github.com/kubenetworks/kubevpn/pull/498 and https://github.com/kubenetworks/kubevpn/pull/496
