### ISSUE TITLE
Error connect tunnel with KubeVPN when IPv6 disable.

### ISSUE THREAD

**Issue by leduyquy** [kubenetworks/kubevpn#244]
Hello. 

I have setup KubeVPN for my cluster but when use kubectl connect to cluster with kubevpn plugin it show error can not setup ipv6. For my company policy, we must disable IPv6 on our computers and not enable it.

Is there any way we can setup a tunnel with kubevpn without enabling IPv6 on my PC?

Thank you.

**Comment by wencaiwulue** [comment]
> Hello.
> 
> I have setup KubeVPN for my cluster but when use kubectl connect to cluster with kubevpn plugin it show error can not setup ipv6. For my company policy, we must disable IPv6 on our computers and not enable it.
> 
> Is there any way we can setup a tunnel with kubevpn without enabling IPv6 on my PC?
> 
> Thank you.

@leduyquy can you provide same log, and which os you are using? macos/windows/linux

**Comment by leduyquy** [comment]
Hi @whomobile 

This is out put log when I connect with IPv6 disable.

![image](https://github.com/kubenetworks/kubevpn/assets/68555139/816ab993-640c-4db2-9181-43d5c4ac9302)
 
I'm using Ubuntu 23.10

**Comment by wencaiwulue** [comment]
> Hi @whomobile
> 
> This is out put log when I connect with IPv6 disable.
> 
> ![image](https://private-user-images.githubusercontent.com/68555139/330258533-816ab993-640c-4db2-9181-43d5c4ac9302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTQ1ODQsIm5iZiI6MTcxNTY1NDI4NCwicGF0aCI6Ii82ODU1NTEzOS8zMzAyNTg1MzMtODE2YWI5OTMtNjQwYy00ZGIyLTkxODEtNDNkNWM0YWM5MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyMzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZTBmNjEwNzMyNzQxY2Q4MzY0MzUxNjVkMjc5NmVmYTQ0MjZhMzNjNWZmZWE1MDI4YjEyZmM0YzY3MDU5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIS-QsPcLNM-943JPUcsD58HxAFXgcaieoJRJdmCiR8)
> 
> I'm using Ubuntu 23.10

got it, by the way. I am @wencaiwulue ...

**Comment by leduyquy** [comment]
Hi @wencaiwulue 

This is result 

![image](https://github.com/kubenetworks/kubevpn/assets/68555139/48a5330c-8114-437f-8030-76a6af321d72)

**Comment by wencaiwulue** [comment]
> Hi @wencaiwulue
> 
> This is result
> 
> ![image](https://private-user-images.githubusercontent.com/68555139/330264928-48a5330c-8114-437f-8030-76a6af321d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTcyMDgsIm5iZiI6MTcxNTY1NjkwOCwicGF0aCI6Ii82ODU1NTEzOS8zMzAyNjQ5MjgtNDhhNTMzMGMtODExNC00MzdmLTgwMzAtNzZhNmFmMzIxZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAzMjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0N2NjMDU5Mzg0NDQ1NGUwM2EyYjYwZDE1Mzc2N2NjM2NkZWEwZjUzMTRhYWRjYzIyMTViNGE5ZDNjNGNlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NLyhhb10F9hyajGXZdXL0ow5p4EXVdLTmFhWbL4OhD0)

ok, got it, i will use this way to detect ipv6 is enable or not. thanks

**Comment by whomobile** [comment]
Hi @wencaiwulue

https://github.com/kubenetworks/kubevpn/blob/984ab2ce89d925352aeff79cbfda3fb89cf7d834/pkg/tun/tun_bsd.go#L58

 cfg.Addr  instead of Addr4 ?

**Comment by wencaiwulue** [comment]
> Hi @wencaiwulue
> 
> https://github.com/kubenetworks/kubevpn/blob/984ab2ce89d925352aeff79cbfda3fb89cf7d834/pkg/tun/tun_bsd.go#L58
> 
> cfg.Addr instead of Addr6 ?
> 
> quick search https://github.com/search?q=repo%3Akubenetworks%2Fkubevpn%20net.ParseCIDR&type=code show other platform use Addr
> 
> but it looks not root cause. https://github.com/kubenetworks/kubevpn/blob/984ab2ce89d925352aeff79cbfda3fb89cf7d834/pkg/tun/tun_bsd.go#L62C3-L62C82

Yes, bug 😂, maybe nobody using kubevpn on bsd system 😂😂😂

**Comment by wencaiwulue** [comment]
@leduyquy commit: https://github.com/kubenetworks/kubevpn/pull/248 can you pull this branch code, and make kubevpn manually? github attachment max size is 50Mb😂

**Comment by wencaiwulue** [comment]
> Hi @wencaiwulue
> 
> https://github.com/kubenetworks/kubevpn/blob/984ab2ce89d925352aeff79cbfda3fb89cf7d834/pkg/tun/tun_bsd.go#L58
> 
> cfg.Addr instead of Addr6 ?
> 
> quick search https://github.com/search?q=repo%3Akubenetworks%2Fkubevpn%20net.ParseCIDR&type=code show other platform use Addr
> 
> but it looks not root cause. https://github.com/kubenetworks/kubevpn/blob/984ab2ce89d925352aeff79cbfda3fb89cf7d834/pkg/tun/tun_bsd.go#L62C3-L62C82

here is commit: https://github.com/kubenetworks/kubevpn/pull/249, please take a review, thanks ~

**Comment by whomobile** [comment]
maybe better check if ipv6 enabled from below.
https://github.com/kubenetworks/kubevpn/blob/cc032c4a6d081266432c600287491c7ae89af90f/pkg/core/route.go#L88

also based on below.  how come even that env var set the value if IPv6 is not enabled? 
https://github.com/search?q=repo%3Akubenetworks%2Fkubevpn%20EnvInboundPodTunIPv6&type=code

It looks like below can be issue when IPv6 is not enabled. 
https://github.com/kubenetworks/kubevpn/blob/cc032c4a6d081266432c600287491c7ae89af90f/pkg/config/config.go#L56

**Comment by leduyquy** [comment]
> @leduyquy commit: #248 can you pull this branch code, and make kubevpn manually? github attachment max size is 50Mb😂

I testing with this branch it working, many thanks.

![image](https://github.com/kubenetworks/kubevpn/assets/68555139/982f373c-6ab0-443e-9330-c1b7666fcba4)

**Comment by wencaiwulue** [comment]
> maybe better check if ipv6 enabled from below.
> 
> https://github.com/kubenetworks/kubevpn/blob/cc032c4a6d081266432c600287491c7ae89af90f/pkg/core/route.go#L88
> 
> also based on below. how come even that env var set the value if IPv6 is not enabled? https://github.com/search?q=repo%3Akubenetworks%2Fkubevpn%20EnvInboundPodTunIPv6&type=code
> 
> It looks like below can be issue when IPv6 is not enabled.
> 
> https://github.com/kubenetworks/kubevpn/blob/cc032c4a6d081266432c600287491c7ae89af90f/pkg/config/config.go#L56

Yes, you are right. If env ipv6 set, means wants to set ipv6 addr. Maybe better way is add flag `--stack` `v4/v6/both/auto`. when we connect to cluster. We can special this option. Set env var more early. Not so late when use it then to check.

**Comment by wencaiwulue** [comment]
> maybe better check if ipv6 enabled from below.
> 
> https://github.com/kubenetworks/kubevpn/blob/cc032c4a6d081266432c600287491c7ae89af90f/pkg/core/route.go#L88
> 
> also based on below. how come even that env var set the value if IPv6 is not enabled? https://github.com/search?q=repo%3Akubenetworks%2Fkubevpn%20EnvInboundPodTunIPv6&type=code
> 
> It looks like below can be issue when IPv6 is not enabled.
> 
> https://github.com/kubenetworks/kubevpn/blob/cc032c4a6d081266432c600287491c7ae89af90f/pkg/config/config.go#L56

I make some change: 14e421c0387c8a4bfb30ceb87802d8c24cf49f6f

**Comment by wencaiwulue** [comment]
@leduyquy already release v2.2.9, you can have a try ~
