### ISSUE TITLE
create deployment kubevpn-traffic-manager pending

### ISSUE THREAD

**Issue by kilawang** [kubenetworks/kubevpn#255]
Hi 

I download v 2.2.9 kubevpn client
and connect my GKE cluster
But the status always pending create deployment

Than I check deployment status , always 0 pod 
It looks like the pod cannot be created

I use Macbook pro 
Cluster Version is 1.27.12-gke.1115000
Clinet is Kubevpn v2.2.9

![截圖 2024-05-17 下午2 46 43](https://github.com/kubenetworks/kubevpn/assets/11882235/877a5d1f-4c28-449c-8e06-95f1ff3eda35)

![截圖 2024-05-17 下午2 47 20](https://github.com/kubenetworks/kubevpn/assets/11882235/8509bff0-76f8-4001-b6d3-0c2b2f9f36c8)

**Comment by wencaiwulue** [comment]
@kilawang can you show apiserver log? maybe pod is block by some webhook.

**Comment by kilawang** [comment]
@wencaiwulue  Thank you for your suggestion. I checked the GKE log.
There is a message that the quota is insufficient.

![截圖 2024-05-17 下午3 46 24](https://github.com/kubenetworks/kubevpn/assets/11882235/95a74f65-a5af-4dca-b47e-7c253802ea70)

But I don’t know what quota settings are needed
I tried adjusting the nodes from 3 to 6 but the problem is still not solved so it shouldn't be a resource issue

**Comment by wencaiwulue** [comment]
Got it you can use this command to remove priorityClassName from deploy
```shell
kubectl patch deployment kubevpn-traffic-manager
 -p '{"spec":{"template":{"spec":{"priorityClassName":null}}}}'
```

**Comment by wencaiwulue** [comment]
> @wencaiwulue Thank you for your suggestion. I checked the GKE log. There is a message that the quota is insufficient.
> 
> ![截圖 2024-05-17 下午3 46 24](https://private-user-images.githubusercontent.com/11882235/331508832-95a74f65-a5af-4dca-b47e-7c253802ea70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzUxMDMsIm5iZiI6MTcxNTkzNDgwMywicGF0aCI6Ii8xMTg4MjIzNS8zMzE1MDg4MzItOTVhNzRmNjUtYTVhZi00ZGNhLWI0N2UtN2MyNTM4MDJlYTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA4MzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YzVlMzg4MGM3ZDcyM2VhZTgxMjY5ZDIyYTY4MWM3MTY3YmMwNTNlMzM5Y2MxNjk3OWY1OWUzN2Q5NWE0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2XsWZBO8nerDR1vmAW81lCqS7yu6iW2wsgnRUQ8vyA)
> 
> But I don’t know what quota settings are needed I tried adjusting the nodes from 3 to 6 but the problem is still not solved so it shouldn't be a resource issue

You can try to edit 
```shell
kubectl describe resourcequota 
```

**Comment by kilawang** [comment]
@wencaiwulue 
Hello, I would like to confirm whether the option to remove this setting parameter can be added in future updates to the settings, or whether it can be listed as optional. Thank you.

Because we currently manage about 19 clusters, and they all need to be manually patched during installation.
This seems unavoidable on GKE

**Comment by wencaiwulue** [comment]
> @wencaiwulue Hello, I would like to confirm whether the option to remove this setting parameter can be added in future updates to the settings, or whether it can be listed as optional. Thank you.
> 
> Because we currently manage about 19 clusters, and they all need to be manually patched during installation. This seems unavoidable on GKE

Yes，i will remove this setting parameter in v2.2.10. do worry about it

**Comment by wencaiwulue** [comment]
@kilawang already released v2.2.10, you can use command `kubevpn upgrade` to have a try ~

**Comment by kilawang** [comment]
@wencaiwulue Thank you, It's work very well

**Comment by kilawang** [comment]
@wencaiwulue Thank you, It's work very well

**Comment by kilawang** [comment]
Thank you, It's work very well

**Comment by kilawang** [comment]
@wencaiwulue Thank you, I upgrade and try it,It's work very well
