### ISSUE TITLE
kubevpn proxy can't across different namespace deploy

### ISSUE THREAD

**Issue by kilawang** [kubenetworks/kubevpn#263]
Hi

I use kubevpn proxy in my default namespace cannot proxy to other namespaces

If I want proxy other namespace deploy , I need create  kubevpn-traffic-manager again in this namespace

Can I use default namespace kubevpn-traffic-manager proxy to any namespace? 
This avoids creating too many kubevpn-traffic-manager

Thank you

**Comment by wencaiwulue** [comment]
It's a good idea, deploy kubevpn to special namespace, then proxy any other namespace workload.
At the project begining. consider permission, maybe someone only have one namespace full permission, can't list another namespace resource, so i decide create deployment kubevpn to current namespace.

**Comment by wencaiwulue** [comment]
> Maybe can consider install kubevpn with helm to ns kubevpn-system. then use this namespace as base namespace? Lots of work to do ~

But that should not happen in the near future

**Comment by kilawang** [comment]
I understand, this is just a suggestion, I hope the function will become more and more perfect

**Comment by wencaiwulue** [comment]
> I understand, this is just a suggestion, I hope the function will become more and more perfect

🤝, thanks for understanding, i wish more and more people to join us and improve the functions. welcome for contributing～

**Comment by leandroblanc** [comment]
@wencaiwulue Hi, thanks for your work on this project and for your feedback. We also use a different namespace per each application and service. Can you at least mention what should be changed so a single KubeVPN installation can be used to access resources in other namespaces? Do you need to change the KubeVPN source code? Or just the Helm Chart manifests? (eg: RBAC config etc). Thanks in advance!

**Comment by wencaiwulue** [comment]
> feedback

Hello,  sorry for late response. Yes, needs to change the source code to meet this feature. Because in the this project beginning, I asume each user will have one unique k8s namespace to deploy their app/service, users do not affect each other. use k8s namespace to isolate resource...

**Comment by leandroblanc** [comment]
Sounds good, thanks for your info!

**Comment by wencaiwulue** [comment]
@kilawang @leandroblanc Good news. we support this feature. you can use version v2.4.3, use helm to install kubevpn server and mutilpe users will use this server, no more to create kubevpn deployment to each other namespce. and proxy workload also support cross namespace. remember use helm to install it. we implement this feature by commit https://github.com/kubenetworks/kubevpn/pull/498 and https://github.com/kubenetworks/kubevpn/pull/496

**Comment by cedricve** [comment]
I did installed through the helm chart, but for some reason I keep getting it's not finding my service to be proxied.

**Comment by wencaiwulue** [comment]
> I did installed through the helm chart, but for some reason I keep getting it's not finding my service to be proxied.

@cedricve Can you show log, it should be RBAC permission issue. 

```go
connectNs, err := util.DetectConnectNamespace(sshCtx, connect.GetFactory(), req.Namespace)
if err != nil {
	return err
}
if connectNs != "" {
	logger.Infof("Use connect namespace %s", connectNs)
	connect.Namespace = connectNs
	req.Namespace = connectNs
} else {
	logger.Infof("Use special namespace %s", req.Namespace)
}
```

if log show `Use connect namespace`, means detect helm installed namespace
