### ISSUE TITLE
How to intercept inbound traffic to a Kubernetes cluster and redirect it to my laptop?

### ISSUE THREAD

**Issue by hexiaodai** [kubenetworks/kubevpn#264]

**Comment by wencaiwulue** [comment]
@hexiaodai you can read doc from here: https://github.com/kubenetworks/kubevpn?tab=readme-ov-file#reverse-proxy

**Comment by hexiaodai** [comment]
> @hexiaodai you can read doc from here: https://github.com/kubenetworks/kubevpn?tab=readme-ov-file#reverse-proxy您可以从这里阅读文档：https://github.com/kubenetworks/kubevpn?tab=readme-ov-file#reverse-proxy

Thank you, the kubevpn project is excellent!

**Comment by hexiaodai** [comment]
> @hexiaodai you can read doc from here: https://github.com/kubenetworks/kubevpn?tab=readme-ov-file#reverse-proxy

Thank you, the kubevpn project is excellent!
