### ISSUE TITLE
Kubevpn alwas use proxy after setting env HTTPS_PROXY

### ISSUE THREAD

**Issue by rucciva** [kubenetworks/kubevpn#268]
hello, i found a weird behavior,
once i run `export HTTPS_PROXY=...` kubevpn will always use that proxy , even after i run `unset HTTPS_PROXY`.
I verified that kubectl itself no longer use that proxy.

is there some kind of cached configuration created by kubevpn?

```
Error: rpc error: code = Unknown desc = failed to get configmap kubevpn-traffic-manager, err: Get "https://<redacted>/api/v1/namespaces/default/configmaps/kubevpn-traffic-manager": proxyconnect tcp: dial tcp 127.0.0.1:1080: connect: connection refused
```

**Comment by wencaiwulue** [comment]
> hello, i found a weird behavior, once i run `export HTTPS_PROXY=...` kubevpn will always use that proxy , even after i run `unset HTTPS_PROXY`. I verified that kubectl itself no longer use that proxy.
> 
> is there some kind of cached configuration created by kubevpn?
> 
> ```
> Error: rpc error: code = Unknown desc = failed to get configmap kubevpn-traffic-manager, err: Get "https://<redacted>/api/v1/namespaces/default/configmaps/kubevpn-traffic-manager": proxyconnect tcp: dial tcp 127.0.0.1:1080: connect: connection refused
> ```

Because kubevpn will startup GRPC server, it will use the env `HTTPS_PROXY` before startup. once server process started. process'env will not change even you unset `HTTPS_PROXY`. So there are no cache configuration.

**Comment by wencaiwulue** [comment]
> is it `kubectl kubevpn quit`? it does seems to fix it. thanks for the clue
> 
> i tried running `kubectl kubevpn reset` before but doesn't seems to fixed it

yes use `kubevpn quit` to quit GRPC server
