### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by Lick-liu** [kubenetworks/kubevpn#302]
1、和ktconnect区别有哪些
2、proxy和dev模式的区别
3、当采用proxy和dev模式时原有的服务实例为什么会被kill掉

**Comment by wencaiwulue** [comment]
> 1、和ktconnect区别有哪些 2、proxy和dev模式的区别 3、当采用proxy和dev模式时原有的服务实例为什么会被kill掉

1，之前有关注过ktconnect，很久没有关注了。
2，proxy 是指把k8s deployment/statusfulset的流量拦截到本地电脑。dev模式也具备这样的功能，不过dev模式会使用本地docker，启动容器，方便自己开发。
3，因为注入了另一个container用于拦截流量，因此deployment的pod会重新创建。

https://www.kubevpn.cn/zh/docs/architecture/connect/ 这里有一些原理图，你可以看看

**Comment by wencaiwulue** [comment]
没有问题就关闭了哈，有问题再开

**Comment by Lick-liu** [comment]
thanks
