### ISSUE TITLE
指定header的反向代理不生效

### ISSUE THREAD

**Issue by A11Might** [kubenetworks/kubevpn#320]
执行命令`kubevpn proxy deployment/xx-test -n xx-dev --image registry.cn-hangzhou.aliyuncs.com/xx/kubevpn:v2.2.17`，可以正常使用本地机器代理节点流量。但执行命令`kubevpn proxy deployment/xx-test -n xx-dev --image registry.cn-hangzhou.aliyuncs.com/xx/kubevpn:v2.2.17 --headers user=naison`，加不加header都无法正常进行请求。应该如何排查这个问题？

**Comment by A11Might** [comment]
命令执行都成功返回：Now you can access resources in the kubernetes cluster, enjoy it :)

**Comment by wencaiwulue** [comment]
@A11Might 使用 `kubevpn list` 看看状态尼？使用了 proxy 么有带header后，需要 kubevpn leave ，然后再 proxy 带header哈

**Comment by A11Might** [comment]
> @A11Might 使用 `kubevpn list` 看看状态尼？使用了 proxy 么有带header后，需要 kubevpn leave ，然后再 proxy 带header哈

尝试了下还是不行，`kubevpn list`执行结果
``` kubevpn list
- Ports: null
  Rules:
  - Headers:
      a: "1"
    LocalTunIPv4: 223.254.0.124
    LocalTunIPv6: efff:ffff:ffff:ffff:ffff:ffff:ffff:99b1
    PortMap: {}
  Uid: deployments.apps/xx-test 
```

**Comment by wencaiwulue** [comment]
> > @A11Might 使用 `kubevpn list` 看看状态尼？使用了 proxy 么有带header后，需要 kubevpn leave ，然后再 proxy 带header哈
> 
> 尝试了下还是不行，`kubevpn list`执行结果
> 
> ```
> - Ports: null
>   Rules:
>   - Headers:
>       a: "1"
>     LocalTunIPv4: 223.254.0.124
>     LocalTunIPv6: efff:ffff:ffff:ffff:ffff:ffff:ffff:99b1
>     PortMap: {}
>   Uid: deployments.apps/xx-test 
> ```

因为你这里的 port是空的，你可以edit 一下 deployment，然后 containerPort 加一下端口就好啦。

**Comment by A11Might** [comment]
> > > @A11Might 使用 `kubevpn list` 看看状态尼？使用了 proxy 么有带header后，需要 kubevpn leave ，然后再 proxy 带header哈
> > 
> > 
> > 尝试了下还是不行，`kubevpn list`执行结果
> > ```
> > - Ports: null
> >   Rules:
> >   - Headers:
> >       a: "1"
> >     LocalTunIPv4: 223.254.0.124
> >     LocalTunIPv6: efff:ffff:ffff:ffff:ffff:ffff:ffff:99b1
> >     PortMap: {}
> >   Uid: deployments.apps/xx-test 
> > ```
> 
> 因为你这里的 port是空的，你可以edit 一下 deployment，然后 containerPort 加一下端口就好啦。

可以啦，感谢。非常好用
