### ISSUE TITLE
同一个k8s集群，如果多个人使用kubevpn就会导致无法访问集群内部地址

### ISSUE THREAD

**Issue by baodelu** [kubenetworks/kubevpn#323]
描述：
A用户是mac系统，B用户是window系统；此时如果两个人都使用kubevpn connect连接到同一个k8s集群，就会导致两个人都不能访问集群网络，请问这个有解决办法吗？

**Comment by wencaiwulue** [comment]
@baodelu 不应该的，应该是都可以访问集群网络才对

**Comment by wencaiwulue** [comment]
@baodelu B用户单独用 windows，可以访问 `kubevpn connect` 连接到k8s 网络吗？就是A用户先不链接

**Comment by baodelu** [comment]
> @baodelu B用户单独用 windows，可以访问 `kubevpn connect` 连接到k8s 网络吗？就是A用户先不链接

如果只是一个用户使用kubevpn是可以访问到集群网络的，A用户和B用户同时使用kubevpn connect的时候就不可以了。比如A用户先连接了集群验证是可以访问集群网络，后来B用户也连接了集群，这时候，A用户再访问集群网络的时候就不行了，然而B用户这时候也不能访问集群网络，感觉像是哪里冲突了。

**Comment by wencaiwulue** [comment]
A用户和B用户的都执行命令 `kubevpn status`，然后把输出内容贴出来我看看尼。

**Comment by wencaiwulue** [comment]
或者用个临时解决办法，A用户和B用户链接到两个不同的namespace，A用户`kubevpn connect -n default` B用户 `kubevpn connect -n test`

**Comment by baodelu** [comment]
> A用户和B用户的都执行命令 `kubevpn status`，然后把输出内容贴出来我看看尼。

A用户（Mac）
baodelu@baodeludeMacBook-Pro:~ $ kubevpn connect --image harbor.cestcywtg.com/rdc-incubator/kubevpn:v2.2.17
Starting connect
Got network CIDR from cache
Use exist traffic manager
Forwarding port...
Connected tunnel
Adding route...
Configured DNS service
+----------------------------------------------------------+
| Now you can access resources in the kubernetes cluster ! |
+----------------------------------------------------------+
baodelu@baodeludeMacBook-Pro:~ $ kubevpn status
ID    Mode   Cluster      Kubeconfig                    Namespace   Status      Netif
0     full   kubernetes   /Users/baodelu/.kube/config   default     Connected   utun5

==================================

B用户（Windows）
C:\Users\DELL>kubevpn connect --image harbor.cestcywtg.com/rdc-incubator/kubevpn:v2.2.17
Starting connect
Got network CIDR from cache
Use exist traffic manager
Forwarding port...
Connected tunnel
Adding route...
Configured DNS service
+----------------------------------------------------------+
| Now you can access resources in the kubernetes cluster ! |
+----------------------------------------------------------+

C:\Users\DELL>kubevpn status
ID    Mode   Cluster      Kubeconfig                   Namespace   Status      Netif
0     full   kubernetes   C:\Users\DELL\.kube\config   default     Connected   KubeVPN

**Comment by wencaiwulue** [comment]
@baodelu https://meeting.tencent.com/dm/hcRxTZfrjy5j 一起看看？

**Comment by wencaiwulue** [comment]
> > A用户和B用户的都执行命令 `kubevpn status`，然后把输出内容贴出来我看看尼。
> 
> A用户（Mac） baodelu@baodeludeMacBook-Pro:~ $ kubevpn connect --image harbor.cestcywtg.com/rdc-incubator/kubevpn:v2.2.17 Starting connect Got network CIDR from cache Use exist traffic manager Forwarding port... Connected tunnel Adding route... Configured DNS service +----------------------------------------------------------+ | Now you can access resources in the kubernetes cluster ! | +----------------------------------------------------------+ baodelu@baodeludeMacBook-Pro:~ $ kubevpn status ID Mode Cluster Kubeconfig Namespace Status Netif 0 full kubernetes /Users/baodelu/.kube/config default Connected utun5
> 
> ==================================
> 
> B用户（Windows） C:\Users\DELL>kubevpn connect --image harbor.cestcywtg.com/rdc-incubator/kubevpn:v2.2.17 Starting connect Got network CIDR from cache Use exist traffic manager Forwarding port... Connected tunnel Adding route... Configured DNS service +----------------------------------------------------------+ | Now you can access resources in the kubernetes cluster ! | +----------------------------------------------------------+
> 
> C:\Users\DELL>kubevpn status ID Mode Cluster Kubeconfig Namespace Status Netif 0 full kubernetes C:\Users\DELL.kube\config default Connected KubeVPN

macOS上：`ifconfig utun5` ,windows 上 `netsh interface ipv4 show addresses KubeVPN` ,看看IP尼

**Comment by baodelu** [comment]
> 给我的感觉像是ip冲突了，也可以简单的，两个电脑都 `kubevpn quit` 退出来，然后其中一个电脑 `kubevpn reset`，然后两个电脑再都链接，看看是否可以尼？

我先尝试一下你这个方法，我昨天又找其他同事验证了一下，有的会冲突，有的就不会冲突，这应该是个例。但具体原因还有待排查

**Comment by baodelu** [comment]
或者有时间你帮我看看，感觉冲突的问题频繁出现

**Comment by wencaiwulue** [comment]
> 或者有时间你帮我看看，感觉冲突的问题频繁出现

好，今晚？

**Comment by wencaiwulue** [comment]
> > 给我的感觉像是ip冲突了，也可以简单的，两个电脑都 `kubevpn quit` 退出来，然后其中一个电脑 `kubevpn reset`，然后两个电脑再都链接，看看是否可以尼？
> 
> 我先尝试一下你这个方法，我昨天又找其他同事验证了一下，有的会冲突，有的就不会冲突，这应该是个例。但具体原因还有待排查

好的，奇怪了，我还没遇到这样的情况尼

**Comment by baodelu** [comment]
> > 或者有时间你帮我看看，感觉冲突的问题频繁出现
> 
> 好，今天什么时候尼

现在就可以，看看我们用什么方法一起排查问题

**Comment by wencaiwulue** [comment]
> > > 或者有时间你帮我看看，感觉冲突的问题频繁出现
> > 
> > 
> > 好，今天什么时候尼
> 
> 现在就可以，看看我们用什么方法一起排查问题

腾讯会议？

**Comment by baodelu** [comment]
> > > > 或者有时间你帮我看看，感觉冲突的问题频繁出现
> > > 
> > > 
> > > 好，今天什么时候尼
> > 
> > 
> > 现在就可以，看看我们用什么方法一起排查问题
> 
> 腾讯会议？

https://meeting.tencent.com/dm/tRx3I4mZqwf0
#腾讯会议：167-331-354

**Comment by wencaiwulue** [comment]
> > > > 或者有时间你帮我看看，感觉冲突的问题频繁出现
> > > 
> > > 
> > > 好，今天什么时候尼
> > 
> > 
> > 现在就可以，看看我们用什么方法一起排查问题
> 
> 腾讯会议？

https://meeting.tencent.com/dm/tBUTgh1d7und
