### ISSUE TITLE
可以提供一个清理 kubevpn-traffic-manager 的命令吗？

### ISSUE THREAD

**Issue by fisherwei** [kubenetworks/kubevpn#363]
比如 kubevpn disconnect --cleanup 这种。

可以将使用过kubevpn的痕迹完全清理掉的。

**Comment by fisherwei** [comment]
是我没有认真看文档。
kubevpn reset
可以实现此功能。

抱歉

**Comment by wencaiwulue** [comment]
@fisherwei 欢迎安利给其他小伙伴哈，也可以顺手给个star，谢啦～
