### ISSUE TITLE
Services implemented based on Netty are experiencing domain name resolution failures.

### ISSUE THREAD

**Issue by 153952402** [kubenetworks/kubevpn#381]
In my Kubernetes setup, there are multiple namespaces, 
one of which is named "mid." Within the "mid" namespace, there is a service named "pulsar-proxy." 
When I try to start my application in IntelliJ IDEA to access **pulsar-proxy.mid.svc.cluster.local**, 
it shows an error indicating that the domain name cannot be resolved. 

However, when I use the curl command in the terminal, it parses successfully."

I'm not very familiar with networking concepts, so if you need any additional information, please let me know.

Based on the code from Netty for parsing domain names, any DNS service with one of the following names can be successfully resolved:
●	cluster.local
●	svc.cluster.local
●	test.svc.cluster.local
However, in reality, the domainToNameServerStreamMap variable only contains svc, local, cluster, local, rather than the complete cluster.local, svc.cluster.local, or test.svc.cluster.local.

![image](https://github.com/user-attachments/assets/b340c49b-bac4-46aa-b245-871ecae9c74e)
![image](https://github.com/user-attachments/assets/66384c67-2697-4fc2-8568-893f28c70690)

**Comment by 153952402** [comment]
![image](https://github.com/user-attachments/assets/4488d848-943d-4a20-b080-b77f3e660447)
![image](https://github.com/user-attachments/assets/ee8c0a84-4e4f-4716-950d-31097ade6bc5)
![image](https://github.com/user-attachments/assets/d716b07c-5ae9-4a45-8294-f805d8aca69c)

**Comment by 153952402** [comment]
![image](https://github.com/user-attachments/assets/f0950eb7-1943-44f1-9d53-8e6503aef459)

**Comment by wencaiwulue** [comment]
Which namespace you are connecting? use command `kubevpn status` to display it, make sure connect to namespace `mid` by command `kubevpn connect -n mid --kubeconfig xxx`

**Comment by 153952402** [comment]
![image](https://github.com/user-attachments/assets/2707f0ca-de64-4753-8d4d-e2d8d73b0d15)
Whether I specify the parameter -n mid or -n default, the DNS resolution still fails in the Java implementation based on Netty. If you need any additional information, please let me know. Thank you very much for your help.

**Comment by wencaiwulue** [comment]
> ![image](https://private-user-images.githubusercontent.com/26498851/390242742-2707f0ca-de64-4753-8d4d-e2d8d73b0d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzkyMDksIm5iZiI6MTczMjY3ODkwOSwicGF0aCI6Ii8yNjQ5ODg1MS8zOTAyNDI3NDItMjcwN2YwY2EtZGU2NC00NzUzLThkNGQtZTJkOGQ3M2IwZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAzNDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjN2E2ZDE1NTYzMzNlYTZhMzU4YTg2MWQxMmFlMzlhNWQ5ZWM4NmYxYjM2NGJkZjg0YmFjZDViZjcwMDIwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5xnSIQ_CrOm6P0JC1_BFhUDT-nHg1A-hhtVf2_Lgpss) ![image](https://private-user-images.githubusercontent.com/26498851/390251348-5dacb27f-47e8-401c-a01a-8e06c4e64cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzkyMDksIm5iZiI6MTczMjY3ODkwOSwicGF0aCI6Ii8yNjQ5ODg1MS8zOTAyNTEzNDgtNWRhY2IyN2YtNDdlOC00MDFjLWEwMWEtOGUwNmM0ZTY0Y2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAzNDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NWQ1YzljNWI4NjQxNmZiMmI5Y2Q2YTJlNTZmYzRmYzEzYjRhZTEzNGE1NTM4NDc1YTZhZGU4MDhjZjQ1YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KCgIOWH4rNytDSZpbcNxXTgvVIlIzlEsW931E12f39M)
> 
> Whether I specify the parameter -n mid or -n default, the DNS resolution still fails in the Java implementation based on Netty. If you need any additional information, please let me know. Thank you very much for your help. @wencaiwulue


Which DNS providers are you using? `DnsServerAddressStreamProviders.unixDefault()` i checked doc `https://netty.io/4.1/api/io/netty/resolver/dns/DnsServerAddressStreamProvider.html` here are many types providers, which one you are using ?

**Comment by 153952402** [comment]
Using the default Provider：  DnsServerAddressStreamProviders.unixDefault()

**Comment by 153952402** [comment]
`public static void main(String[] args) throws InterruptedException {
        String domainName = "pulsar-proxy.mid";
        try {
            // use jdk inner Class InetAddress  for resolve
            InetAddress[] addresses = InetAddress.getAllByName(domainName);
            // resolve success, print: 172.18.251.70
            Arrays.stream(addresses).forEach(address -> System.out.println(address.getHostAddress()));

            // use netty
            NioEventLoopGroup group = new NioEventLoopGroup(1);
            try {
                DnsNameResolver resolver = new DnsNameResolverBuilder(group.next()).channelType(NioDatagramChannel.class)
                        .nameServerProvider(DnsServerAddressStreamProviders.unixDefault()).build();
                Future<List<InetAddress>> future = resolver.resolveAll(domainName);
                List<InetAddress> inetAddresses = future.sync().getNow();
                for (InetAddress inetAddress : inetAddresses) {
                    //java.net.UnknownHostException: Failed to resolve 'pulsar-proxy.mid.svc.cluster.local' [A(1), AAAA(28)] after 6 queries
                    System.out.println(inetAddress);
                }
            } finally {
                group.shutdownGracefully();
            }
        } catch (UnknownHostException e) {
            System.err.println("Unable to resolve domain: " + domainName);
            e.printStackTrace();
        }
    }`

**Comment by wencaiwulue** [comment]
> Using the default Provider： DnsServerAddressStreamProviders.unixDefault()

i mean which implement you are using 

> Interface DnsServerAddressStreamProvider
All Known Implementing Classes:
[DefaultDnsServerAddressStreamProvider](https://netty.io/4.1/api/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.html), [MacOSDnsServerAddressStreamProvider](https://netty.io/4.1/api/io/netty/resolver/dns/macos/MacOSDnsServerAddressStreamProvider.html), [MultiDnsServerAddressStreamProvider](https://netty.io/4.1/api/io/netty/resolver/dns/MultiDnsServerAddressStreamProvider.html), [SequentialDnsServerAddressStreamProvider](https://netty.io/4.1/api/io/netty/resolver/dns/SequentialDnsServerAddressStreamProvider.html), [SingletonDnsServerAddressStreamProvider](https://netty.io/4.1/api/io/netty/resolver/dns/SingletonDnsServerAddressStreamProvider.html), [UnixResolverDnsServerAddressStreamProvider](https://netty.io/4.1/api/io/netty/resolver/dns/UnixResolverDnsServerAddressStreamProvider.html)

**Comment by 153952402** [comment]
"Although my computer is macOS, I am using `UnixResolverDnsServerAddressStreamProvider`."

**Comment by 153952402** [comment]
I saw this issue in the Netty project, but I still couldn't resolve it. 
Apart from the Netty issue, can you explain why nslookup can't find it, but curl can?

**Comment by wencaiwulue** [comment]
1.  nslookup does not use `/etc/resolver`. but we add dns config to `/etc/resolver/xxx`. so curl works but nslookup failed
2. maybe you can `copy /etc/resolver/local /etc/resolver/cluster.local` and then use netty to test it if works or not ?

**Comment by 153952402** [comment]
Thank you for your help.
1. After executing the command cp /etc/resolver/local /etc/resolver/cluster.local, the Netty test passed, and I was able to successfully resolve all domain names ending with .svc.cluster.local. However, I couldn't resolve the shorthand domain name pulsar-proxy.mid unless I copied it again and named it pulsar-proxy.mid.
2. I have replaced the implementation class as described in netty issues #11020, but neither MacOSDnsServerAddressStreamProvider nor UnixResolverDnsServerAddressStreamProvider could resolve the domain, both throwing the same error. However, after performing the copy, domain resolution succeeds with either implementation class.
3. So, is it possible to modify kubevpn to automatically generate files like pulsar-proxy.mid and cluster.local?

![image](https://github.com/user-attachments/assets/eab6e013-092e-42ed-a35f-3b7eabe7bfbd)
![image](https://github.com/user-attachments/assets/52ac267e-12db-47fd-ba2f-2002b75bf791)

**Comment by wencaiwulue** [comment]
> Thank you for your help.
> 
> 1. Based on the domain name resolution logic in the Java Netty project's code, it seems that the filenames under /etc/resolver/ should be at least two-part (e.g., `cluster.local`), as a single-part name like `local` is not meaningful. I think there's a reason for this code logic because a typical domain name should have at least two parts, such as google.com or amazon.com. A single "com" on its own doesn't make sense as it is a top-level domain.
> 2. After executing the command` cp /etc/resolver/local /etc/resolver/cluster.local`, the Netty test passed, and I was able to successfully resolve `pulsar-proxy.mid.svc.cluster.local` and  all domain names ending with `cluster.local`. However, I couldn't resolve the shorthand domain name `pulsar-proxy.mid` **unless I copied it again and named it `pulsar-proxy.mid`.**
> 3. I have replaced the implementation class as described in netty issues #11020, but neither MacOSDnsServerAddressStreamProvider or UnixResolverDnsServerAddressStreamProvider could not resolve the domain, both throwing the same error. However, after performing the copy, domain resolution succeeds with either implementation class.
> 4. So, is it possible to modify kubevpn to automatically generate files like `pulsar-proxy.mid` and `cluster.local`?
> 
> ![image](https://private-user-images.githubusercontent.com/26498851/390690479-eab6e013-092e-42ed-a35f-3b7eabe7bfbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTAzMjMsIm5iZiI6MTczMjc5MDAyMywicGF0aCI6Ii8yNjQ5ODg1MS8zOTA2OTA0NzktZWFiNmUwMTMtMDkyZS00MmVkLWEzNWYtM2I3ZWFiZTdiZmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEwMzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYTAzNTI4OGNmNjVjMTQ3NWI2OTRhODhiOTliMGNmN2RhZjJmZjI2YzNjZDMwMWE2NDUyZWE5Yzc5ZGE0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QgDQc6CjM1eJjs_PNxZcKC5zi0iAZBMVRTRn8g-dGpQ) ![image](https://private-user-images.githubusercontent.com/26498851/390690664-52ac267e-12db-47fd-ba2f-2002b75bf791.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTAzMjMsIm5iZiI6MTczMjc5MDAyMywicGF0aCI6Ii8yNjQ5ODg1MS8zOTA2OTA2NjQtNTJhYzI2N2UtMTJkYi00N2ZkLWJhMmYtMjAwMmI3NWJmNzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEwMzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNmY4ZWZlZTgxNTc3YWZhNzM3NTBmZWFjMTExYWNhZjFlMWRkMGUyYjMyMWE3ZjUzZWFmYmFjYmRhMzdiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1dB8KMPAt9Cjv0e-igMejJy-qMV-iE8f6EZT_bAdw9o)

Cool.
1. Of course, kubevpn can generate `/etc/resolver/cluster.local` and `/etc/resolver/pulsar-proxy.mid` .

**Comment by wencaiwulue** [comment]
> I'm also not sure whether this issue should be resolved in the kubevpn project or in the netty project. If you confirm that kubevpn has done what it needs to do and no further fixes or optimizations are necessary, then we will close this issue.

Yes, do worry about it, it is kubevpn's problem

**Comment by wencaiwulue** [comment]
@153952402 if you use full name eg `pulsar-proxy.mid.svc.cluster.local`, not needs to copy `/etc/resolver`, it's ok or not ?

**Comment by teocns** [comment]
I think this is not a Netty issue?
Latest release didn't work for me, downgraded to `2.2.22` and things regained vitality

**Comment by 153952402** [comment]
> @153952402 if you use full name eg `pulsar-proxy.mid.svc.cluster.local`, not needs to copy `/etc/resolver`, it's ok or not ?

If you want Netty to resolve the `pulsar-proxy.mid `domain name, there must be a `pulsar-proxy.mid` file in the /etc/resolver directory.

If you want Netty to resolve the `pulsar-proxy.mid.cluster.local` domain name, you need to have at least one of the following files in the /etc/resolver directory: `cluster.local` or` mid.cluster.local`.

If I don't make any copy operations, Netty will not be able to resolve any domain names, regardless of whether I use `pulsar-proxy` or `pulsar-proxy.mid.svc.cluster.local`. According to Netty's code logic, files in the /etc/resolver directory must contain at least two segments; otherwise, it will use the default 127.0.0.1 for domain name resolution.

**Comment by wencaiwulue** [comment]
> I think this is not a Netty issue? Latest release of KubeVPN simply didn't work for me with similar resolution issues, downgraded to `2.2.22` and things regained vitality.
> 
> ```
> vpn 2024-11-27 01:20:18 tunhandler.go:120 debug: [TUN] SRC: fe80::6d32:bb25:796d:8c27 --> DST: ff02::16, length: 136                                                                    
> vpn 2024-11-27 01:20:18 tunhandler.go:407 error: [TUN] No route for src: fe80::6d32:bb25:796d:8c27 -> dst: ff02::16, drop it  
> ```

Do you have same DNS resolve issue? can you description what you meet ?

**Comment by wencaiwulue** [comment]
> > @153952402 if you use full name eg `pulsar-proxy.mid.svc.cluster.local`, not needs to copy `/etc/resolver`, it's ok or not ?
> 
> If I don't make any copy operations, Netty will not be able to resolve any domain names, regardless of whether I use `pulsar-proxy` or `pulsar-proxy.mid.svc.cluster.local`.
> 
> If you want Netty to resolve the `pulsar-proxy.mid `domain name, there must be a `pulsar-proxy.mid` file in the /etc/resolver directory.
> 
> If you want Netty to resolve the `pulsar-proxy.mid.cluster.local` domain name, you need to have at least one of the following files in the /etc/resolver directory: `cluster.local` or `svc.cluster.local` or `mid.svc.cluster.local`.
> 
> According to Netty's code logic, The file names under /etc/resolver must have at least two segments; otherwise, it will use the default name server(127.0.0.1) for domain name resolution.
> 
> ![image](https://private-user-images.githubusercontent.com/26498851/390978170-b14f2e23-58de-4e11-9787-d735f5cdb9b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjA4MjksIm5iZiI6MTczMjg2MDUyOSwicGF0aCI6Ii8yNjQ5ODg1MS8zOTA5NzgxNzAtYjE0ZjJlMjMtNThkZS00ZTExLTk3ODctZDczNWY1Y2RiOWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA2MDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMTQ2ZDlmY2EyN2JkNWQ0MjYxNGM2ZjI5ZjI3OTY3ZmFiNDA5MTU3ZDRkZjRjN2E4NzE3YzQzNjZmNGZiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TPd7vg__Tsy4OFIrgBoe2mtmLw-Lu09ZvbL8tZnTI7w)
> 
> @wencaiwulue

Got it, how about if i create files like bellow: 
- `/etc/resolver/local`
- `/etc/resolver/cluster.local`
- `/etc/resolver/svc.cluster.local`
- `/etc/resolver/mid.svc.cluster.local`

it should support domain name like this , right ?
- `pulsar-proxy.mid`
- `pulsar-proxy.mid.cluster`
- `pulsar-proxy.mid.cluster.local`

**Comment by 153952402** [comment]
No No No
if you create files like bellow:

- /etc/resolver/local
- /etc/resolver/cluster.local
- /etc/resolver/svc.cluster.local
- /etc/resolver/mid.svc.cluster.local

it should support domain name like this
1. any domain  end with` cluster.local`
2. any domain end with` svc.cluster.local`
3. any domain end with `mid.svc.cluster.local`

so `pulsar-proxy.mid` and `pulsar-proxy.mid.svc` can'be resolve
only `pulsar-proxy.mid.svc.cluster.local` will be resolve success

**Comment by wencaiwulue** [comment]
> No No No if you create files like bellow:
> 
> * /etc/resolver/local
> * /etc/resolver/cluster.local
> * /etc/resolver/svc.cluster.local
> * /etc/resolver/mid.svc.cluster.local
> 
> it should support domain name like this
> 
> 1. any domain  end with` cluster.local`
> 2. any domain end with` svc.cluster.local`
> 3. any domain end with `mid.svc.cluster.local`
> 
> so `pulsar-proxy.mid` and `pulsar-proxy.mid.svc` can'be resolve only `pulsar-proxy.mid.svc.cluster.local` will be resolve success

if you create file named `/etc/resolver/.mid` ，domain `pulsar-proxy.mid` should works fine，right？

**Comment by 153952402** [comment]
no ` /etc/resolver/.mid` or ` /etc/resolver/mid.` will be ignore, because The file names under /etc/resolver must have at **least two segments**;

**Comment by wencaiwulue** [comment]
> I think this is not a Netty issue? Latest release of KubeVPN simply didn't work for me with similar resolution issues, downgraded to `2.2.22` and things regained vitality.
> 
> ```
> vpn 2024-11-27 01:20:18 tunhandler.go:120 debug: [TUN] SRC: fe80::6d32:bb25:796d:8c27 --> DST: ff02::16, length: 136                                                                    
> vpn 2024-11-27 01:20:18 tunhandler.go:407 error: [TUN] No route for src: fe80::6d32:bb25:796d:8c27 -> dst: ff02::16, drop it  
> ```

@teocns i found the reason why newer kubevpn not works. because `docker.io/naison/kubevpn:v2.3.3` was be coverd by a image with bug. i just build new image `docker.io/naison/kubevpn:v2.3.3`, it should works fine, thanks for report this issue

**Comment by teocns** [comment]
thanks - you might wanna push a revision to invalidate cache on worker nodes without having to alter  `imagePullPolicy` for whom has already pulled the faulty one

**Comment by wencaiwulue** [comment]
> thanks - you might wanna push a revision tag to invalidate cache on worker nodes without having to alter `imagePullPolicy` for whom has already pulled the faulty one

Do you means i need to change deploy `kubevpn-traffic-manager` `imagePullPolicy` from `IfNotPresent` to `Always`?

**Comment by wencaiwulue** [comment]
@teocns i recommend you can use newer version `v2.3.4` and image use `docker.io/naison/kubevpn:v2.3.4` or `ghcr.io/kubenetworks/kubevpn:v2.3.4`, just upgrade to ~ 😄

**Comment by wencaiwulue** [comment]
> thanks - you might wanna push a revision tag to invalidate cache on worker nodes without having to alter `imagePullPolicy` for whom has already pulled the faulty one

yes, we can push a new revision tag `v2.3.3` or `v2.3.4` to invalidate cache on worker nodes. but still pod needs to restart to use newer image

**Comment by wencaiwulue** [comment]
> thanks - you might wanna push a revision tag to invalidate cache on worker nodes without having to alter `imagePullPolicy` for whom has already pulled the faulty one

Yes, you are right, because now, the image pull policy is `IfNotPresent`, if we just restart deploy, it will not pull newer image. we needs to push newer image to worker node, and then restart deploy. thanks, finally, understand what you said 👍

**Comment by 153952402** [comment]
Thanks, I have updated the latest version, and it works perfectly on my computer now.
@wencaiwulue
