### ISSUE TITLE
--extra-domain flag adding host file entry with ip set to <nil>

### ISSUE THREAD

**Issue by th3fallen** [kubenetworks/kubevpn#394]
running `kubevpn proxy deployment/company-js --extra-domain appx.company.net`

and my hosts file after looks like...

```
<nil> appx.company.net  # Add by KubeVPN
10.43.10.54   worktags                 # Add by KubeVPN
10.43.128.159 company-js             # Add by KubeVPN
10.43.134.58  tasks-api-private        # Add by KubeVPN
10.43.197.148 tasks-api                # Add by KubeVPN
10.43.151.224 sqssns                   # Add by KubeVPN
10.43.148.47  sqs-admin                # Add by KubeVPN
10.43.53.14   shifts-public            # Add by KubeVPN
10.43.47.171  shifts-private           # Add by KubeVPN
10.43.251.64  redis                    # Add by KubeVPN
10.43.207.209 mysql                    # Add by KubeVPN
10.43.112.204 monolith                 # Add by KubeVPN
10.43.234.252 minio                    # Add by KubeVPN
10.43.238.222 login-private-rpc        # Add by KubeVPN
10.43.70.143  login-private            # Add by KubeVPN
10.43.18.233  login-js                 # Add by KubeVPN
10.43.242.94  login-data-plumber       # Add by KubeVPN
10.43.78.85   login                    # Add by KubeVPN
10.43.111.46  ld-relay                 # Add by KubeVPN
10.43.55.58   kubevpn-traffic-manager  # Add by KubeVPN
10.43.39.136  kafka-dev                # Add by KubeVPN
10.43.215.3   dynamodb                 # Add by KubeVPN
10.43.61.142  data-plumber             # Add by KubeVPN
10.43.226.133 company                  # Add by KubeVPN
```

**Comment by wencaiwulue** [comment]
> running `kubevpn proxy deployment/company-js --extra-domain appx.company.net`
> 
> and my hosts file after looks like...
> 
> ```
> <nil> appx.company.net  # Add by KubeVPN
> 10.43.10.54   worktags                 # Add by KubeVPN
> 10.43.128.159 company-js             # Add by KubeVPN
> 10.43.134.58  tasks-api-private        # Add by KubeVPN
> 10.43.197.148 tasks-api                # Add by KubeVPN
> 10.43.151.224 sqssns                   # Add by KubeVPN
> 10.43.148.47  sqs-admin                # Add by KubeVPN
> 10.43.53.14   shifts-public            # Add by KubeVPN
> 10.43.47.171  shifts-private           # Add by KubeVPN
> 10.43.251.64  redis                    # Add by KubeVPN
> 10.43.207.209 mysql                    # Add by KubeVPN
> 10.43.112.204 monolith                 # Add by KubeVPN
> 10.43.234.252 minio                    # Add by KubeVPN
> 10.43.238.222 login-private-rpc        # Add by KubeVPN
> 10.43.70.143  login-private            # Add by KubeVPN
> 10.43.18.233  login-js                 # Add by KubeVPN
> 10.43.242.94  login-data-plumber       # Add by KubeVPN
> 10.43.78.85   login                    # Add by KubeVPN
> 10.43.111.46  ld-relay                 # Add by KubeVPN
> 10.43.55.58   kubevpn-traffic-manager  # Add by KubeVPN
> 10.43.39.136  kafka-dev                # Add by KubeVPN
> 10.43.215.3   dynamodb                 # Add by KubeVPN
> 10.43.61.142  data-plumber             # Add by KubeVPN
> 10.43.226.133 company                  # Add by KubeVPN
> ```

@th3fallen can you make sure domain `appx.company.net` can be resolve in pod `kubevpn-traffic-manager` or not ?

**Comment by wencaiwulue** [comment]
@th3fallen already release new version，you can have a try～
