### ISSUE TITLE
How to use this tool on the Rancher platform？

### ISSUE THREAD

**Issue by kooksee** [KubeNetworks/kubevpn#44]

**Comment by wencaiwulue** [comment]
You can download kubeconfig to local
<img width="1919" alt="image" src="https://github.com/KubeNetworks/kubevpn/assets/33818115/41a549dc-1041-4944-a8cf-f79c71ab4791">
Then, use it as normal kubernetes cluster
<img width="1920" alt="image" src="https://github.com/KubeNetworks/kubevpn/assets/33818115/72167a02-cd23-455c-b423-1787d59e247f">
