### ISSUE TITLE
aws container root access warning

### ISSUE THREAD

**Issue by kooksee** [KubeNetworks/kubevpn#46]
<img width="624" alt="image" src="https://github.com/KubeNetworks/kubevpn/assets/6829652/9ec3e978-1726-47b9-9b31-c39ae7f108cc">

An alarm was triggered for AWS monitoring, and its permissions were too large, which may result in unexpected operations？

**Comment by wencaiwulue** [comment]
> 

Because in traffic-manager pod， it will to create tun device and use iptables to forward traffic. So it needs privillage permission

**Comment by wencaiwulue** [comment]
@kooksee If you don't want to create pod with `privillage` permission, you can use `--netstack gvisor` mode. this mode will not needs privillage permission. ref: https://www.kubevpn.cn/docs/architecture/gvisor_mesh
