### ISSUE TITLE
Installation through "krew" doesn't work as described

### ISSUE THREAD

**Issue by salimd** [KubeNetworks/kubevpn#51]
Installation through `kubectl krew` is failing due to missing artifact.

```
└─▪ kubectl krew index add kubevpn https://github.com/KubeNetworks/kubevpn.git
WARNING: You have added a new index from "https://github.com/KubeNetworks/kubevpn.git"
The plugins in this index are not audited for security by the Krew maintainers.
Install them at your own risk.
```

```
└─▪ kubectl krew install kubevpn/kubevpn
Updated the local copy of plugin index.
Updated the local copy of plugin index "kubevpn".
Installing plugin: kubevpn
W0717 11:53:39.616542   93538 install.go:164] failed to install plugin "kubevpn": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.34/kubevpn_v1.1.34_darwin_amd64.zip", status code 404
failed to install some plugins: [kubevpn]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.34/kubevpn_v1.1.34_darwin_amd64.zip", status code 404
```

**Comment by wencaiwulue** [comment]
> Installation through `kubectl krew` is failing due to missing artifact.
> 
> ```
> └─▪ kubectl krew index add kubevpn https://github.com/KubeNetworks/kubevpn.git
> WARNING: You have added a new index from "https://github.com/KubeNetworks/kubevpn.git"
> The plugins in this index are not audited for security by the Krew maintainers.
> Install them at your own risk.
> ```
> 
> ```
> └─▪ kubectl krew install kubevpn/kubevpn
> Updated the local copy of plugin index.
> Updated the local copy of plugin index "kubevpn".
> Installing plugin: kubevpn
> W0717 11:53:39.616542   93538 install.go:164] failed to install plugin "kubevpn": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.34/kubevpn_v1.1.34_darwin_amd64.zip", status code 404
> failed to install some plugins: [kubevpn]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.34/kubevpn_v1.1.34_darwin_amd64.zip", status code 404
> ```

oh， no, i forgot it. now i have fixed this bug, please try it again

**Comment by salimd** [comment]
Confirmed, it is working now. Thanks!

```
└─▪ kubectl krew install kubevpn/kubevpn
Updated the local copy of plugin index.
Updated the local copy of plugin index "kubevpn".
Installing plugin: kubevpn
Installed plugin: kubevpn
\
 | Use this plugin:
 | 	kubectl kubevpn
 | Documentation:
 | 	https://github.com/KubeNetworks/kubevpn
/
```
