### ISSUE TITLE
No pods run, connect failed

### ISSUE THREAD

**Issue by alairock** [KubeNetworks/kubevpn#53]
```
$ kubectl kubevpn connect --debug                                                                                                                                                           
get cidr from cluster info...
get cidr from cluster info ok
get cidr from cni...
wait pod cni-net-dir-kubevpn to be running timeout, reason , ignore
get cidr from svc...
get cidr from svc ok
traffic manager not exist, try to create it...
```

Then it just sits there, doing nothing for eternity. Never moves passed this. No pods run.  After running `kubevpn reset` and starting it again, a pod `cni-net-dir-kubevpn` begins to be created, but never finishes. After the timeout message happens, the pod disappears. There is also a deployment called `kubevpn-traffic-manager` with 0/0 ready.

**Comment by wencaiwulue** [comment]
> ```
> $ kubectl kubevpn connect --debug                                                                                                                                                           
> get cidr from cluster info...
> get cidr from cluster info ok
> get cidr from cni...
> wait pod cni-net-dir-kubevpn to be running timeout, reason , ignore
> get cidr from svc...
> get cidr from svc ok
> traffic manager not exist, try to create it...
> ```
> 
> Then it just sits there, doing nothing for eternity. Never moves passed this. No pods run. After running `kubevpn reset` and starting it again, a pod `cni-net-dir-kubevpn` begins to be created, but never finishes. After the timeout message happens, the pod disappears. There is also a deployment called `kubevpn-traffic-manager` with 0/0 ready.

pod `cni-net-dir-kubevpn` doesn't matter. create it just want to get cidr range gracefully. the really needs to concern problem is why `kubevpn-traffic-manager` with 0/0 ready. maybe you can describe this deployment or see logs from api-server?

**Comment by alairock** [comment]
I think I just needed a good night sleep. Looked at the deployment status:

`message: 'insufficient quota to match these scopes: [{PriorityClass In [system-node-critical`

Looks like I just ran out of room to run it. What is the minimum requirement? Maybe I can still squeeze it on an existing node.

**Comment by wencaiwulue** [comment]
> 

It will create a pod with three containers, each container needs memory: 250mb and cpu: 0.5c. actually you can edit this deployment, decrease resources and remove priorityclass, let node schedule it. also you can add a new k8s node.

**Comment by alairock** [comment]
The actual solution, in my case (using GKE) was to set the value of `priority_class_name` to `""` (empty string). 

In case anyone runs into this in the future.

**Comment by wencaiwulue** [comment]
> 

Can you connect to k8s network now? like ping pod ip in local

**Comment by alairock** [comment]
Yes, btw, sorry for the delay. All is well.

**Comment by wencaiwulue** [comment]
@alairock commit is here: https://github.com/kubenetworks/kubevpn/commit/28f6d543981688cfe0c8644968230c3c320017b0
