### ISSUE TITLE
kubevpn connect --ssh-addr error desc = not an ip:port

### ISSUE THREAD

**Issue by whomobile** [KubeNetworks/kubevpn#79]
It looks like even if all ssh configuration correct, it failed with below error. 
```
kubevpn connect --ssh-addr 192.168.1.100:22 --ssh-username root --ssh-keyfile ~/.ssh/ssh.pem --foreground=true
Error: rpc error: code = Unknown desc = not an ip:port
```

ahd kubevpn logs or debug=true does not generate any logs.

**Comment by wencaiwulue** [comment]
> It looks like even if all ssh configuration correct, it failed with below error.
> 
> ```
> kubevpn connect --ssh-addr 192.168.1.100:22 --ssh-username root --ssh-keyfile ~/.ssh/ssh.pem --foreground=true
> Error: rpc error: code = Unknown desc = not an ip:port
> ```
> 
> ahd kubevpn logs or debug=true does not generate any logs.

you can use kubevpn logs -f to see more log

**Comment by wencaiwulue** [comment]
i will comfire this issue and fix it as soon as possible

**Comment by wencaiwulue** [comment]
<img width="1732" alt="image" src="https://github.com/KubeNetworks/kubevpn/assets/33818115/cc27c276-02e3-441c-ab9e-b4c5ed361b7a">


> It looks like even if all ssh configuration correct, it failed with below error.
> 
> ```
> kubevpn connect --ssh-addr 192.168.1.100:22 --ssh-username root --ssh-keyfile ~/.ssh/ssh.pem --foreground=true
> Error: rpc error: code = Unknown desc = not an ip:port
> ```
> 
> ahd kubevpn logs or debug=true does not generate any logs.

i tested it and it works well, you can upgrade it to latest version by command `kubevpn upgrade` and try it again? 


maybe it is because you do not special remote cluster kubeconfig or special option `--remote-kubeconfig`, this option means kubevpn will use ssh server ~/.kube/config file to connect to cluster or you can copy this file to local , and special --kubeconfig or export env like k8s kubectl

**Comment by whomobile** [comment]
❯ kubevpn upgrade
The latest version is: v2.1.0, commit: fa4943175245b449aa786113d7577514755e27d2
Already up to date, don't needs to upgrade
Upgrade daemon...done

![Screenshot 2023-10-30 at 7 22 33 PM](https://github.com/KubeNetworks/kubevpn/assets/474397/d2feef0c-37a6-4805-8470-bc8b941c191e)

My environment is macos ventua 13.4, just in case. 

normally it works fine. 

![Screenshot 2023-10-30 at 7 26 15 PM](https://github.com/KubeNetworks/kubevpn/assets/474397/b27bae2d-28f5-477e-97ec-5e7da45df809)

**Comment by whomobile** [comment]
by the way, I test ssh server with/without ~/.kube/config 
based on timing, it looks not even try to connect remote.

**Comment by wencaiwulue** [comment]
can you exec command `kubevpn version` and show me output?

**Comment by whomobile** [comment]
![Screenshot 2023-10-30 at 7 40 55 PM](https://github.com/KubeNetworks/kubevpn/assets/474397/20c21e12-ca22-4581-85be-c4a35e5c7aad)

**Comment by wencaiwulue** [comment]
no needs to quit daemon by command `kubevpn quit`, daemon server will do nothing if client not send any command to server. the reason why i startup a daemon server is because can connect to mutiple cluster

**Comment by wencaiwulue** [comment]
maybe we can have a online meeting by feishu or tencent meeting? to diagnose issue ? if you have some time

**Comment by whomobile** [comment]
sure, we can talk your time morning (my time evening), let me know time.

**Comment by wencaiwulue** [comment]
> sure, we can talk your time morning (my time evening), let me know time.

ok, here is my wechat: fcw895703375

**Comment by whomobile** [comment]
Sorry, my wechat account got logged out and can't recover it.  Here is larksuite meeting we can use. 

Meeting topic: kubevpn
Meeting time: Tomorrow, Nov 1, 8:00 - 8:30 PM (GMT-7)
Meeting ID: 954 040 901
Meeting link: https://vc.larksuite.com/j/954040901

**Comment by wencaiwulue** [comment]
> Sorry, my wechat account got logged out and can't recover it. Here is larksuite meeting we can use.
> 
> Meeting topic: kubevpn Meeting time: Tomorrow, Nov 1, 8:00 - 8:30 PM (GMT-7) Meeting ID: 954 040 901 Meeting link: https://vc.larksuite.com/j/954040901

ok ,got it, meeting start timestamp should is 1698894000 . right? because i am in chain, GMT+8, in case of mistake the time

**Comment by whomobile** [comment]
yes next 10minutes :-)

**Comment by wencaiwulue** [comment]
> yes next 10minutes :-) . started the meeting. Thanks

Maybe you can use comand `kubectl config view --flatten --raw` and save output , use this kubeconfig to connect via ssh. i noticed that when we try to connect to via ssh, we have see log like `kubeconfig is invalid`, and i checked code, this message only shows while kubeconfig is not configured correctly
<img width="933" alt="image" src="https://github.com/KubeNetworks/kubevpn/assets/33818115/b0b4247b-7859-4c77-8351-b77ba51463b0">
