### ISSUE TITLE
kubectl kubevpn ssh --ssh-addr .. causing it keep try to download new version

### ISSUE THREAD

**Issue by whomobile** [KubeNetworks/kubevpn#80]
**Installed as krew plugin case:**

It looks like it check whether need to upgrade kubevpn but only check /usr/local/bin (or kubevpn version).

workaround is copy kubectl-kubevpn to /usr/local/bin/kubevpn

**Comment by whomobile** [comment]
(by the way, didn't say that, this is fantastic tool, thanks for make it happen. saving time from build stunnels)

**Comment by wencaiwulue** [comment]
> **Installed as krew plugin case:**
> 
> It looks like it check whether need to upgrade kubevpn but only check /usr/local/bin (or kubevpn version).
> 
> workaround is copy kubectl-kubevpn to /usr/local/bin/kubevpn

if you are use krew , you can use upgrade kubevpn by `kubectl krew upgrade kubevpn` or `kubectl kubevpn upgrade` it's ok

**Comment by wencaiwulue** [comment]
i am confusing, `kubectl kubevpn ssh --ssh-addr .. causing it keep try to download new version` ? what's that mean? kubevpn client will NOT upgrade auto, only will upgarde remote k8s pod image if client version is bigger than pod image version

**Comment by wencaiwulue** [comment]
> i am confusing, `kubectl kubevpn ssh --ssh-addr .. causing it keep try to download new version` ? what's that mean? kubevpn client will NOT upgrade auto, only will upgarde remote k8s pod image while connectting to cluster if client version is bigger than pod image version

because client version should match pod image version

**Comment by whomobile** [comment]
![Screenshot 2023-10-30 at 7 32 47 PM](https://github.com/KubeNetworks/kubevpn/assets/474397/8275bde3-3ef4-41bc-bfed-d8d9c9f13f53)

**Comment by whomobile** [comment]
![Screenshot 2023-10-30 at 7 32 47 PM](https://github.com/KubeNetworks/kubevpn/assets/474397/5515f476-a88e-4124-9e55-8bef1f63d407)

check video.
https://vimeo.com/879639601/1c3f56eb87?share=copy

**Comment by wencaiwulue** [comment]
yes this function have bugs :( , i found it after released v2.1.0, otherwise i will fix it... ok for now, you can install kubevpn to remote linux server, put it into /usr/local/bin/kubevpn linux server , on you mac you can use kubevpn ssh --ssh-addr xxxx to connect

**Comment by wencaiwulue** [comment]
> ![Screenshot 2023-10-30 at 7 32 47 PM](https://user-images.githubusercontent.com/474397/279242099-5515f476-a88e-4124-9e55-8bef1f63d407.png)
> 
> check video. https://vimeo.com/879639601/1c3f56eb87?share=copy

yse it is very clear

**Comment by wencaiwulue** [comment]
> > ![Screenshot 2023-10-30 at 7 32 47 PM](https://user-images.githubusercontent.com/474397/279242099-5515f476-a88e-4124-9e55-8bef1f63d407.png)
> > check video. https://vimeo.com/879639601/1c3f56eb87?share=copy
> 
> yse it is very clear

i mixed kubevpn ssh and kubevpn connect with ssh two function ....
