### ISSUE TITLE
Can't run control-plane

### ISSUE THREAD

**Issue by SakaZhang** [KubeNetworks/kubevpn#89]
kubevpn connect: 
```
pod kubevpn-traffic-manager-847dbd46c-9thpr is Running
Container     Reason           Message
control-plane CrashLoopBackOff back-off 40s restarting failed container=control-plane pod=kubevpn-traffic-manager-847dbd46c-9thpr_default(dc8489b6-fbfd-415c-85ee-c6acd93f06d3)
vpn           ContainerRunning
webhook       ContainerRunning
```
kubectl logs:
```
kubectl logs kubevpn-traffic-manager-847dbd46c-9thpr -c control-plane
failed to create file watcher, err: too many open files
```
ulimit on the node:
```
root@node3:/home/minum# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 63555
max locked memory           (kbytes, -l) 2048064
max memory size             (kbytes, -m) unlimited
open files                          (-n) 128000
```

**Comment by wencaiwulue** [comment]
> kubevpn connect:
> 
> ```
> pod kubevpn-traffic-manager-847dbd46c-9thpr is Running
> Container     Reason           Message
> control-plane CrashLoopBackOff back-off 40s restarting failed container=control-plane pod=kubevpn-traffic-manager-847dbd46c-9thpr_default(dc8489b6-fbfd-415c-85ee-c6acd93f06d3)
> vpn           ContainerRunning
> webhook       ContainerRunning
> ```
> 
> kubectl logs:
> 
> ```
> kubectl logs kubevpn-traffic-manager-847dbd46c-9thpr -c control-plane
> failed to create file watcher, err: too many open files
> ```
> 
> ulimit on the node:
> 
> ```
> root@node3:/home/minum# ulimit -a
> real-time non-blocking time  (microseconds, -R) unlimited
> core file size              (blocks, -c) 0
> data seg size               (kbytes, -d) unlimited
> scheduling priority                 (-e) 0
> file size                   (blocks, -f) unlimited
> pending signals                     (-i) 63555
> max locked memory           (kbytes, -l) 2048064
> max memory size             (kbytes, -m) unlimited
> open files                          (-n) 128000
> ```

which version you are using? you are use command `kubevpn version` and paste output ？

**Comment by SakaZhang** [comment]
> > kubevpn connect:
> > ```
> > pod kubevpn-traffic-manager-847dbd46c-9thpr is Running
> > Container     Reason           Message
> > control-plane CrashLoopBackOff back-off 40s restarting failed container=control-plane pod=kubevpn-traffic-manager-847dbd46c-9thpr_default(dc8489b6-fbfd-415c-85ee-c6acd93f06d3)
> > vpn           ContainerRunning
> > webhook       ContainerRunning
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > kubectl logs:
> > ```
> > kubectl logs kubevpn-traffic-manager-847dbd46c-9thpr -c control-plane
> > failed to create file watcher, err: too many open files
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ulimit on the node:
> > ```
> > root@node3:/home/minum# ulimit -a
> > real-time non-blocking time  (microseconds, -R) unlimited
> > core file size              (blocks, -c) 0
> > data seg size               (kbytes, -d) unlimited
> > scheduling priority                 (-e) 0
> > file size                   (blocks, -f) unlimited
> > pending signals                     (-i) 63555
> > max locked memory           (kbytes, -l) 2048064
> > max memory size             (kbytes, -m) unlimited
> > open files                          (-n) 128000
> > ```
> 
> which version you are using? you are use command `kubevpn version` and paste output ？

```
 $ kubevpn version
KubeVPN: CLI
    Version: v1.1.34
    Image: docker.io/naison/kubevpn:v1.1.34
    Branch: HEAD
    Git commit: b0ed57794f15d71c0886b86d965252051aec4d30
    Built time: 2023-07-17 09:16:55
    Built OS/Arch: linux/amd64
    Built Go version: go1.19.11
```
And here is the output:
```
pod kubevpn-traffic-manager-55ffd7568-5qjs2 is Running
Container     Reason           Message
control-plane CrashLoopBackOff back-off 20s restarting failed container=control-plane pod=kubevpn-traffic-manager-55ffd7568-5qjs2_default(c97e9b1d-619c-4ef1-befb-04aad0501ce7)
vpn           ContainerRunning
webhook       ContainerRunning

pod kubevpn-traffic-manager-55ffd7568-5qjs2 is Running
Container     Reason           Message
control-plane Error
vpn           ContainerRunning
webhook       ContainerRunning
```

**Comment by wencaiwulue** [comment]
> > > kubevpn connect:
> > > ```
> > > pod kubevpn-traffic-manager-847dbd46c-9thpr is Running
> > > Container     Reason           Message
> > > control-plane CrashLoopBackOff back-off 40s restarting failed container=control-plane pod=kubevpn-traffic-manager-847dbd46c-9thpr_default(dc8489b6-fbfd-415c-85ee-c6acd93f06d3)
> > > vpn           ContainerRunning
> > > webhook       ContainerRunning
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > kubectl logs:
> > > ```
> > > kubectl logs kubevpn-traffic-manager-847dbd46c-9thpr -c control-plane
> > > failed to create file watcher, err: too many open files
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ulimit on the node:
> > > ```
> > > root@node3:/home/minum# ulimit -a
> > > real-time non-blocking time  (microseconds, -R) unlimited
> > > core file size              (blocks, -c) 0
> > > data seg size               (kbytes, -d) unlimited
> > > scheduling priority                 (-e) 0
> > > file size                   (blocks, -f) unlimited
> > > pending signals                     (-i) 63555
> > > max locked memory           (kbytes, -l) 2048064
> > > max memory size             (kbytes, -m) unlimited
> > > open files                          (-n) 128000
> > > ```
> > 
> > 
> > which version you are using? you are use command `kubevpn version` and paste output ？
> 
> ```
>  $ kubevpn version
> KubeVPN: CLI
>     Version: v1.1.34
>     Image: docker.io/naison/kubevpn:v1.1.34
>     Branch: HEAD
>     Git commit: b0ed57794f15d71c0886b86d965252051aec4d30
>     Built time: 2023-07-17 09:16:55
>     Built OS/Arch: linux/amd64
>     Built Go version: go1.19.11
> ```
> 
> And here is the output:
> 
> ```
> pod kubevpn-traffic-manager-55ffd7568-5qjs2 is Running
> Container     Reason           Message
> control-plane CrashLoopBackOff back-off 20s restarting failed container=control-plane pod=kubevpn-traffic-manager-55ffd7568-5qjs2_default(c97e9b1d-619c-4ef1-befb-04aad0501ce7)
> vpn           ContainerRunning
> webhook       ContainerRunning
> 
> pod kubevpn-traffic-manager-55ffd7568-5qjs2 is Running
> Container     Reason           Message
> control-plane Error
> vpn           ContainerRunning
> webhook       ContainerRunning
> ```

version is too old, can you upgrade it from https://github.com/KubeNetworks/kubevpn/releases/tag/v2.1.1, after upgrade, use command `kubevpn reset` to reset , and try connect again ?

**Comment by SakaZhang** [comment]
> > > > kubevpn connect:
> > > > ```
> > > > pod kubevpn-traffic-manager-847dbd46c-9thpr is Running
> > > > Container     Reason           Message
> > > > control-plane CrashLoopBackOff back-off 40s restarting failed container=control-plane pod=kubevpn-traffic-manager-847dbd46c-9thpr_default(dc8489b6-fbfd-415c-85ee-c6acd93f06d3)
> > > > vpn           ContainerRunning
> > > > webhook       ContainerRunning
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > kubectl logs:
> > > > ```
> > > > kubectl logs kubevpn-traffic-manager-847dbd46c-9thpr -c control-plane
> > > > failed to create file watcher, err: too many open files
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ulimit on the node:
> > > > ```
> > > > root@node3:/home/minum# ulimit -a
> > > > real-time non-blocking time  (microseconds, -R) unlimited
> > > > core file size              (blocks, -c) 0
> > > > data seg size               (kbytes, -d) unlimited
> > > > scheduling priority                 (-e) 0
> > > > file size                   (blocks, -f) unlimited
> > > > pending signals                     (-i) 63555
> > > > max locked memory           (kbytes, -l) 2048064
> > > > max memory size             (kbytes, -m) unlimited
> > > > open files                          (-n) 128000
> > > > ```
> > > 
> > > 
> > > which version you are using? you are use command `kubevpn version` and paste output ？
> > 
> > 
> > ```
> >  $ kubevpn version
> > KubeVPN: CLI
> >     Version: v1.1.34
> >     Image: docker.io/naison/kubevpn:v1.1.34
> >     Branch: HEAD
> >     Git commit: b0ed57794f15d71c0886b86d965252051aec4d30
> >     Built time: 2023-07-17 09:16:55
> >     Built OS/Arch: linux/amd64
> >     Built Go version: go1.19.11
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And here is the output:
> > ```
> > pod kubevpn-traffic-manager-55ffd7568-5qjs2 is Running
> > Container     Reason           Message
> > control-plane CrashLoopBackOff back-off 20s restarting failed container=control-plane pod=kubevpn-traffic-manager-55ffd7568-5qjs2_default(c97e9b1d-619c-4ef1-befb-04aad0501ce7)
> > vpn           ContainerRunning
> > webhook       ContainerRunning
> > 
> > pod kubevpn-traffic-manager-55ffd7568-5qjs2 is Running
> > Container     Reason           Message
> > control-plane Error
> > vpn           ContainerRunning
> > webhook       ContainerRunning
> > ```
> 
> version is too old, can you upgrade it from https://github.com/KubeNetworks/kubevpn/releases/tag/v2.1.1, after upgrade, use command `kubevpn reset` to reset , and try connect again ?

OK, I'll try it later. Thanks.

**Comment by SakaZhang** [comment]
Now i upgrade kubevpn to v2.1.1 and the problem is still there.
```
pod kubevpn-traffic-manager-b988d65d5-85wcd is Running
Container     Reason           Message
control-plane ContainerRunning
vpn           ContainerRunning
webhook       ContainerRunning

Creating mutatingWebhook_configuration for kubevpn-traffic-manager
update ref count successfully
port forward ready
tunnel connected
adding route...
dns service ok
+---------------------------------------------------------------------------+
|    Now you can access resources in the kubernetes cluster, enjoy it :)    |
+---------------------------------------------------------------------------+
```
and the process exited with code 0.
Here is control-plane log:
```
 $ kubectl logs kubevpn-traffic-manager-b988d65d5-85wcd -c control-plane
failed to create file watcher, err: too many open files
 $ kubectl get pods
NAME                                      READY   STATUS             RESTARTS      AGE
kubevpn-traffic-manager-b988d65d5-85wcd   2/3     CrashLoopBackOff   2 (26s ago)   58s
```

**Comment by wencaiwulue** [comment]
> Now i upgrade kubevpn to v2.1.1 and the problem is still there.
> 
> ```
> pod kubevpn-traffic-manager-b988d65d5-85wcd is Running
> Container     Reason           Message
> control-plane ContainerRunning
> vpn           ContainerRunning
> webhook       ContainerRunning
> 
> Creating mutatingWebhook_configuration for kubevpn-traffic-manager
> update ref count successfully
> port forward ready
> tunnel connected
> adding route...
> dns service ok
> +---------------------------------------------------------------------------+
> |    Now you can access resources in the kubernetes cluster, enjoy it :)    |
> +---------------------------------------------------------------------------+
> ```
> 
> and the process exited with code 0. Here is control-plane log:
> 
> ```
>  $ kubectl logs kubevpn-traffic-manager-b988d65d5-85wcd -c control-plane
> failed to create file watcher, err: too many open files
>  $ kubectl get pods
> NAME                                      READY   STATUS             RESTARTS      AGE
> kubevpn-traffic-manager-b988d65d5-85wcd   2/3     CrashLoopBackOff   2 (26s ago)   58s
> ```

can you make sure, your k8s node which pod scheduled is ok or not? and more , this pod `kubevpn-traffic-manager-b988d65d5-85wcd` can create or vim file now ?

**Comment by SakaZhang** [comment]
All look like good.
```
 $ kubectl exec -it kubevpn-traffic-manager-55ffd7568-dtzm9  -- bash
Defaulted container "vpn" out of: vpn, control-plane, webhook
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app# ls
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app# vim test.file
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app# cat test.file
Sdfasd

 $ kubectl exec -it kubevpn-traffic-manager-55ffd7568-dtzm9 -c control-plane -- bash
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app#
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app#
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app# ls
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app# vim test.file
root@kubevpn-traffic-manager-55ffd7568-dtzm9:/app# cat test.file
asdfasdfg
```

**Comment by wencaiwulue** [comment]
It looks like this line occours error.
<img width="1221" alt="image" src="https://github.com/KubeNetworks/kubevpn/assets/33818115/f6fc1dbf-d9e7-4986-bce2-c814c76f9cad">

can you ref this doc https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files adjust config?

**Comment by wencaiwulue** [comment]
control-plane failed, only effect service mesh function, you can also ping pod_ip, it should works well.

**Comment by SakaZhang** [comment]
> It looks like this line occours error. <img alt="image" width="1221" src="https://user-images.githubusercontent.com/33818115/281364473-f6fc1dbf-d9e7-4986-bce2-c814c76f9cad.png">
> 
> can you ref this doc https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files adjust config?

I adjust this kernel parameter and kubevpn is running now. Thank you.
But i wonder why lead this problem? Because it seems not very many watcher in my cluster.
