### ISSUE TITLE
`kubevpn connect` hangs indefinitely while waiting for Pod before Deployment is created

### ISSUE THREAD

**Issue by jarimayenburg** [KubeNetworks/kubevpn#93]
I was just trying out `kubevpn` for the first time and `kubevpn connect` kept hanging just before creating the Deployment
```
/tmp/kubevpn master !1 ❯ ./bin/kubevpn connect                                                                                                                              ✘ INT  8 21:29:25
start to connect
get cidr from cluster info...
get cidr from cluster info ok
get cidr from cni...
get cidr from cni ok
get cidr from svc...
get cidr from svc ok
get cidr successfully
traffic manager not exist, try to create it...
label namespace default
create serviceAccount kubevpn-traffic-manager
create roles kubevpn-traffic-manager
create roleBinding kubevpn-traffic-manager
create service kubevpn-traffic-manager
create deployment kubevpn-traffic-manager
```

I had a look at `pkg/handler/remote.go` and saw that the Pod watchstream is started before the Deployment is created
https://github.com/KubeNetworks/kubevpn/blob/99601693d3eb6a773ca870604e0a22940f881e97/pkg/handler/remote.go#L391-L402

My namespace is empty before kubevpn is started, so this command hangs indefinitely. After moving the watch command to after the Deployment is created, everything works fine. Fix is in #94.

I'm not sure how this hasn't happened to anyone else yet though. Is it expected that `clientset.CoreV1().Pods(namespace).Watch()` hangs if no matching pod is found? I'm running Kubernetes v1.26.6.

**Comment by wencaiwulue** [comment]
> I was just trying out `kubevpn` for the first time and `kubevpn connect` kept hanging just before creating the Deployment
> 
> ```
> /tmp/kubevpn master !1 ❯ ./bin/kubevpn connect                                                                                                                              ✘ INT  8 21:29:25
> start to connect
> get cidr from cluster info...
> get cidr from cluster info ok
> get cidr from cni...
> get cidr from cni ok
> get cidr from svc...
> get cidr from svc ok
> get cidr successfully
> traffic manager not exist, try to create it...
> label namespace default
> create serviceAccount kubevpn-traffic-manager
> create roles kubevpn-traffic-manager
> create roleBinding kubevpn-traffic-manager
> create service kubevpn-traffic-manager
> create deployment kubevpn-traffic-manager
> ```
> 
> I had a look at `pkg/handler/remote.go` and saw that the Pod watchstream is started before the Deployment is created
> 
> https://github.com/KubeNetworks/kubevpn/blob/99601693d3eb6a773ca870604e0a22940f881e97/pkg/handler/remote.go#L391-L402
> 
> My namespace is empty before kubevpn is started, so this command hangs indefinitely. After moving the watch command to after the Deployment is created, everything works fine. Fix is in #94.
> 
> I'm not sure how this hasn't happened to anyone else yet though. Is it expected that `clientset.CoreV1().Pods(namespace).Watch()` hangs if no matching pod is found? I'm running Kubernetes v1.26.6.

Do you connectted to clutser network finally or not ?

**Comment by jarimayenburg** [comment]
Yes, after moving the pod watcher to after the Deployment is created everything worked perfectly

**Comment by wencaiwulue** [comment]
> watchStream, err := clientset.CoreV1().Pods(namespace).Watch(ctx, metav1.ListOptions{ 
>  	LabelSelector: fields.OneTermEqualSelector("app", config.ConfigMapPodTrafficManager).String(), 
>  }) 
>  if err != nil { 
>  	log.Errorf("Failed to create watch for %s: %v", config.ConfigMapPodTrafficManager, err) 
>  	return err 
>  } 
>  defer watchStream.Stop()

ok, that's great, actually you can delete lines from 391 to 398, because those codes not need anymore, the reason why i write the code is in the begining, i want to use k8s listAndWatch to wait pod to be ready, but soon afterwards， i changed it to use list, because of permission, if i use listAndWatch, i need list and watch deployment permission, but if only use list, i just need list deployment permission. so i changed it
